// Manual only: npm run server:bundle && node scripts/qa/rooms.mjs
import assert from 'node:assert/strict';
import {runRoom} from '../../supabase/functions/_shared/room-engine.js';
const start=1800000030000;
const members=Array.from({length:5},(_,slot)=>({user_id:`user-${slot}`,slot,last_seen:new Date(start).toISOString()}));
const profiles=members.map(m=>({user_id:m.user_id,state:null}));
let now=start,room=null;
const call=(user,commands=[],extra={})=>{
 now+=200;
 const result=runRoom(structuredClone(room),members,profiles,user,{id:crypto.randomUUID(),input:{x:0,z:0},commands:commands.map(([kind,value])=>({id:crypto.randomUUID(),kind,value})),...extra},now);
 room=JSON.parse(JSON.stringify(result.room));return result.response;
};
call('user-0');
assert.equal(Object.keys(room.players).length,5);
assert.deepEqual(Object.values(room.players).map(p=>p.runtime.fields.farmSlot),[0,1,2,3,4]);
const before=room.players['user-0'].runtime.save.dust;
call('user-0',[],{save:{dust:1e12},x:99999,z:-99999,dt:1e12});
assert.equal(room.players['user-0'].runtime.save.dust,before);
assert.equal(room.players['user-0'].runtime.fields.x,0);
assert.equal(room.players['user-0'].runtime.fields.z,0);
const egg=room.world.find(e=>e.stageId===1&&e.type===0);
assert.ok(egg);
for(const id of ['user-0','user-1'])Object.assign(room.players[id].runtime.fields,{x:egg.x,z:egg.z,deadline:now+45000});
assert.equal(call('user-0',[['pickup',egg.id]]).errors.length,0);
assert.ok(call('user-1',[['pickup',egg.id]]).errors.includes('EGG_UNAVAILABLE'));
assert.equal(room.world.filter(e=>e.id===egg.id).length,0);
assert.equal(Object.values(room.players).filter(p=>p.runtime.fields.carried?.id===egg.id).length,1);
Object.assign(room.players['user-0'].runtime.fields,{x:0,z:0});
call('user-0');
assert.equal(room.players['user-0'].runtime.save.eggs.filter(e=>e.id===egg.id).length,1);
const id=crypto.randomUUID(),request=crypto.randomUUID();
call('user-0',[],{id:request,commands:[{id,kind:'sellEgg',value:egg.id}]});
const sold=room.players['user-0'].runtime.save.dust;
call('user-0',[],{id:request,commands:[{id,kind:'sellEgg',value:egg.id}]});
assert.equal(room.players['user-0'].runtime.save.dust,sold);
assert.ok(call('user-1',[['sellEgg',egg.id]]).runtime.save.eggs.length===0);
assert.ok(call('user-0',[['upgrade','__proto__']]).errors.includes('INVALID_UPGRADE'));
assert.ok(call('user-0',[['equip',319]]).errors.includes('NOT_OWNED'));
const other=runRoom(null,members,profiles,'user-0',{id:crypto.randomUUID(),commands:[]},now).room;
assert.notEqual(other.world[0].id,room.world[0].id);
console.log('PASS: shared egg claim, replay, private inventory, forged save/position rejection, farm slots, room RNG');

// Manual regression: room-authoritative moving melee and exactly-once egg drop.
let combat=JSON.parse(JSON.stringify(other));
const attacker=combat.players['user-0'],victim=combat.players['user-1'];
const loot=combat.world.shift();
for(const p of Object.values(combat.players))Object.assign(p.runtime.fields,{x:6,z:0});
Object.assign(attacker.runtime.fields,{x:0,z:-8,facing:{x:0,z:-1},batAt:0});
Object.assign(victim.runtime.fields,{x:0,z:-9,carried:loot,deadline:now+45000});
Object.assign(combat.players['user-2'].runtime.fields,{x:0,z:-6});
const attackId=crypto.randomUUID(),attackRequest=crypto.randomUUID();
const strike={id:attackRequest,input:{x:0,z:-1},commands:[{id:attackId,kind:'attack'}]};
let hit=runRoom(combat,members,profiles,'user-0',strike,now+30);
assert.deepEqual(hit.response.errors,[]);
assert.equal(hit.room.players['user-1'].runtime.fields.carried,null);
assert.equal(hit.room.world.filter(e=>e.id===loot.id).length,1);
assert.ok(hit.room.players['user-1'].runtime.fields.knockback.remaining>0);
assert.equal(hit.room.players['user-2'].runtime.fields.knockedUntil,0);
assert.deepEqual(hit.room.players['user-0'].input,{x:0,z:-1});
const downUntil=hit.room.players['user-1'].runtime.fields.knockedUntil;
hit=runRoom(JSON.parse(JSON.stringify(hit.room)),members,profiles,'user-0',strike,now+80);
assert.equal(hit.room.players['user-1'].runtime.fields.knockedUntil,downUntil);
assert.equal(hit.room.world.filter(e=>e.id===loot.id).length,1);
assert.ok(hit.room.players['user-1'].runtime.fields.z<-9);
const swingAt=hit.room.players['user-0'].runtime.fields.batAt;
hit=runRoom(JSON.parse(JSON.stringify(hit.room)),members,profiles,'user-0',{...strike,id:crypto.randomUUID(),commands:[{id:crypto.randomUUID(),kind:'attack'}]},now+130);
assert.equal(hit.room.players['user-0'].runtime.fields.batAt,swingAt);
console.log('PASS: melee facing, retained input, knockback, shared drop, replay and cooldown');
