export type ArtCluster={zone:string;name:string;items:string};
export type EnvironmentArt={name:string;heights:number[];floor:number[];accents:number[];mediums:string;backdrops:string;detail:string;clusters:ArtCluster[]};
const c=(zone:string,name:string,items:string):ArtCluster=>({zone,name,items});
/** Authored production manifest: one landmark, four structures and six related scenes. */
export const ENVIRONMENT_ART:EnvironmentArt[]=[
 {name:'몽글 초원',heights:[1,0,-1,2,0,0,2,0],floor:[0xc7ad7a,0x8ca776,0xa8b887],accents:[0xe4d9b2,0xcfa085,0xd1bc75],mediums:'C:brook D:flower-hill E:watermill F:mushroom-stump',backdrops:'tree tree house',detail:'leaf',clusters:[
  c('A','피크닉','blanket basket fruit*3 flower*2'),c('B','풀숲','fern sprout*4 pebble*2'),c('C','개울','reed*3 rock*4 branch'),c('D','꽃밭','flower*7 hive'),c('F','그루터기','log mushroom*3 acorn*4'),c('G','뿌리집','root*3 door petal*4')]},
 {name:'장난감 왕국',heights:[1,0,0,2,-1,0,2,0],floor:[0xd1a774,0xc3b59c,0xe0cfaa],accents:[0xbd786b,0xd8b66e,0x8196b5],mediums:'C:pencil-fort D:book-mountain E:station H:toy-chest',backdrops:'desk-leg cushion toy-chest',detail:'paper',clusters:[
  c('A','포장','gift*3 ribbon paper*4'),c('B','그림','pencil*3 eraser crumb*4 scribble'),c('C','요새','fence*3 brick*5 pencil flag'),c('D','독서','book*7 blanket bookmark'),c('E','기차역','toy suitcase*2 rail sign'),c('F','정리 전','cup pencil-broken*3 open-book paper*4')]},
 {name:'심해 산호숲',heights:[0,-1,2,0,0,2,3,0],floor:[0xd5c9a1,0x8ba9a4,0xb6c4b5],accents:[0xc78fa7,0x9b8db1,0xe5dfcc],mediums:'C:sponge-grove D:shipwreck E:kelp-garden F:clam-reef',backdrops:'coral ship mast',detail:'sand',clusters:[
  c('A','조개밭','clam shell*4 sand'),c('B','해저 흔적','anchor chain bottle*2 sand'),c('C','해면','sponge*5 coral*2'),c('D','난파선','plank*4 chest seaweed*3'),c('E','해초','seaweed*7 rock*2'),c('G','진주','clam pearl coral*4 shard*3')]},
 {name:'화산 대장간',heights:[0,0,3,-2,1,0,2,0],floor:[0x64626a,0x49474f,0x805c4e],accents:[0xd88643,0xc0a268,0x819c9a],mediums:'C:basalt D:lava-basin E:forge-bench F:ore-yard',backdrops:'chimney basalt cliff',detail:'crack',clusters:[
  c('A','연료','coal*4 basket shovel ash'),c('B','광석','ore*5 cart shard*3'),c('C','식은 용암','rock*3 lava ash*3'),c('E','단조','anvil hammer*2 tongs shard*4'),c('F','냉각','bucket ingot*3 puddle'),c('G','화로','bellows chain log*3 ember')]},
 {name:'유령 학교',heights:[0,0,1,0,2,-1,2,0],floor:[0xa18a70,0x817c85,0xb7a28b],accents:[0x75998d,0xa495b4,0xe1d6b9],mediums:'C:classroom-board D:locker-row E:library F:piano',backdrops:'school-wall school-wall shelf',detail:'paper',clusters:[
  c('A','수업','desk chair open-book*2 pencil'),c('B','준비물','suitcase pouch chalk-box'),c('C','교단','eraser chalk*4 crumb*4'),c('D','사물함','locker-open ball coat paper*3'),c('E','독서','book*6 bookend bookmark'),c('F','음악','paper*3 chair bell float-book')]},
 {name:'네온 사이버시티',heights:[1,0,0,2,-1,0,3,0],floor:[0x687780,0x82929d,0x4e6072],accents:[0x82b7b8,0xa794bd,0xc79883],mediums:'A:shopfront C:charging-bay D:air-conditioning F:food-stall',backdrops:'city-tower city-tower antenna',detail:'tile',clusters:[
  c('A','상점','vending crate*3 sign mat'),c('B','통신','antenna cabinet cable*3'),c('C','충전','charger*2 battery stool'),c('D','공조','fan pipe filter-box bolt*4'),c('F','포장마차','stall board chair*2 cup'),c('G','탑','cabinet cable-reel lamp*2 hologram')]},
 {name:'황금 사막왕국',heights:[0,2,-1,0,3,0,2,0],floor:[0xd8bf88,0xc7a877,0xe4ce9a],accents:[0x87aea0,0xb68476,0xc8ad70],mediums:'C:oasis D:caravan E:ruined-columns F:excavation',backdrops:'dune pyramid cliff',detail:'sand',clusters:[
  c('A','여행','jar*3 cloth suitcase'),c('B','건조 식생','dry-shrub*2 rock*4 bone'),c('C','오아시스','palm*3 reed jar'),c('D','상단','tent blanket chest*2 lantern'),c('E','유적','ruin*3 relief sand'),c('F','발굴','shovel sieve crate slab')]},
 {name:'태초의 공룡섬',heights:[1,0,0,2,0,-2,3,0],floor:[0xa08769,0x6f8d6a,0x557568],accents:[0x9fac6a,0x7ba6a0,0xd8d0ac],mediums:'C:fern-grove D:ribcage E:fallen-tree F:jungle-falls',backdrops:'root tree fern',detail:'leaf',clusters:[
  c('A','뿌리','root*2 vine*3 leaf'),c('B','포자','mushroom*5 rock'),c('C','양치','fern*7 leaf*3'),c('D','화석','bone*5 fossil rock*3'),c('E','거목','log bark*3 fruit*4'),c('F','물가','moss-rock*3 leaf*2 ripple')]},
 {name:'도깨비 달마을',heights:[0,-1,1,0,2,0,0,2],floor:[0xa398a8,0x947f69,0x6d8f83],accents:[0xc9ac76,0x85a79c,0xbf9da5],mediums:'C:market D:well E:totems H:gazebo',backdrops:'tile-roof bamboo moon',detail:'grain',clusters:[
  c('A','주막','jar*3 chair lantern'),c('B','연못','rock*4 reed lantern'),c('C','장터','tent basket*3 cloth sign'),c('D','우물','bucket rope jar*2'),c('E','소원','totem*2 knot*3 pebble*4'),c('H','정자','cushion*2 cup drum lantern')]},
 {name:'올림포스 신전',heights:[0,0,2,-1,0,1,3,0],floor:[0xe0ddcd,0xb1b7b3,0x9eaeb7],accents:[0xc5af73,0x91a5b5,0x84986b],mediums:'C:colonnade D:statue-fountain E:laurel-garden F:winged-statue',backdrops:'colonnade temple cloud',detail:'tile',clusters:[
  c('A','참배','amphora*3 cloth flower*2'),c('B','유적','ruin*3 slab*2'),c('C','열주','torch bench wreath'),c('D','수반','ripple statue rock*3'),c('E','정원','laurel*2 flower*4 amphora'),c('F','제단','scroll harp shield wreath')]},
 {name:'외계인 51구역',heights:[1,0,-1,2,0,0,3,0],floor:[0x9ba8a6,0x8c9e84,0x777d98],accents:[0xacbe86,0xa498b8,0x92b8ad],mediums:'C:alien-grove D:culture-tank E:observatory-dish F:research-console',backdrops:'ufo alien-grove antenna',detail:'grain',clusters:[
  c('A','표본','specimen*2 bottle*3 lamp paper'),c('B','전력','battery*2 cable cabinet'),c('C','식생','mushroom tentacle*4 spore'),c('D','배양','tank pipe*2 valve stool'),c('E','관측','dish tripod crate'),c('F','실험','console chair open-book specimen')]},
 {name:'스팀펑크 공중도시',heights:[0,1,0,2,-1,0,3,0],floor:[0xae9377,0x7f9096,0x706a60],accents:[0xc4a56e,0x839f98,0xe0d5b8],mediums:'C:boiler-room D:gear-engine F:airship-dock H:station',backdrops:'airship chimney tower',detail:'grain',clusters:[
  c('A','여행','suitcase*3 sign bench'),c('B','정비','tools*4 desk barrel'),c('C','보일러','pipe*3 valve*2 coal'),c('D','동력','gear*3 axle gauge bolt*3'),c('F','정박','cable-reel crate*3 bollard'),c('H','휴식','teapot cup*2 chair paper')]},
 {name:'영원의 빙하',heights:[1,0,-1,2,0,0,3,0],floor:[0xbacdd1,0xe3ece9,0x91becb],accents:[0x91bcbf,0x8e97b4,0xcaa67a],mediums:'C:frozen-lake D:ice-spires E:polar-camp F:buried-sled',backdrops:'ice-spires cliff pine',detail:'snow',clusters:[
  c('A','바람눈','snowball*3 crystal*4'),c('B','숲','fir*2 moss-rock*3'),c('C','호수','crack snowball shard*3'),c('D','빙주','icicle*6'),c('E','캠프','tent lantern chest*2 blanket'),c('F','탐험','sled suitcase flag footprints')]},
 {name:'뒤죽박죽 꿈나라',heights:[0,1,0,2,-1,0,3,0],floor:[0xe2d8bd,0xc4b0cc,0xd5bdc9],accents:[0xae9fbe,0xd3ac97,0xe2cf99],mediums:'C:card-fan D:giant-teacup E:floating-door F:cloud-sofa',backdrops:'bedpost blanket cloud',detail:'paper',clusters:[
  c('A','잠자리','cushion*3 blanket slippers'),c('B','편지','envelope*3 key book'),c('C','카드','card*7 dice'),c('D','티타임','cup teapot spoon plate*2'),c('E','시간','clock chain paper*3'),c('F','휴식','sofa cushion*2 umbrella float-book')]},
 {name:'방사능 폐허',heights:[0,0,2,-1,1,0,2,0],floor:[0x92978b,0x817769,0x71876c],accents:[0xa2b77b,0xad8865,0xd5cbb3],mediums:'C:bus-wreck D:reclaimed-pool E:planter-beds F:broken-office',backdrops:'ruin greenhouse beam',detail:'crack',clusters:[
  c('A','정리','crate*2 lamp shovel rubble'),c('B','식생','sprout*5 moss-rock*3 pot'),c('C','교통','tire*3 chair slab'),c('D','배관','pipe*3 valve barrel'),c('E','재배','pot*4 watering-can seed-packet tools'),c('F','관제','monitor desk cable paper*4')]},
 {name:'곤충 소인국',heights:[1,0,-1,2,0,0,3,0],floor:[0xb4a17e,0x97ac70,0x73825e],accents:[0xc79886,0xd2bd76,0x9ebfb1],mediums:'C:dew-basin D:acorn-workshop E:leaf-shelter F:honeycomb',backdrops:'grass-stems dandelion flower',detail:'vein',clusters:[
  c('A','씨앗','seed*6 pebble*4'),c('B','잎','dry-leaf*2 leafbud*3 pebble*2'),c('C','물가','dew*2 shell reed*4'),c('D','작업','acorn branch*3 fruit'),c('E','쉼터','leaf chair*2 pollen'),c('F','벌집','honeycomb-piece*3 wax flower*3')]},
 {name:'고철 로봇행성',heights:[0,1,0,2,-1,0,3,0],floor:[0x989c9b,0x6f838d,0x927c63],accents:[0xb5a172,0x85a7a4,0xcca46d],mediums:'C:sorting-bench D:assembly-arm F:rotor-generator H:scrap-bin',backdrops:'robot-hand crane beam',detail:'tile',clusters:[
  c('A','체결','bolt*5 nut*3 tools'),c('B','적재','pallet battery*3 slab*2'),c('C','분류','wheel*3 gear*3 crate'),c('D','조립','desk hand tongs lamp'),c('E','정비','pipe*3 cable-reel barrel'),c('F','동력','rotor coil*2 cabinet cable')]},
 {name:'은하수 천문대',heights:[1,0,0,2,-1,0,3,0],floor:[0xc6c7d1,0x8b8fa4,0xaaa2bb],accents:[0xc7b47d,0xa0bfcb,0xb0a0c3],mediums:'C:planetarium D:telescope E:meteor-garden F:archive',backdrops:'nebula planets dome',detail:'tile',clusters:[
  c('A','관측','bench telescope scroll'),c('B','기록','book*3 star-chart pencil'),c('C','행성계','orb planets orbit'),c('D','장비','tripod lens crate'),c('E','운석','moonrock shard*5 specimen'),c('F','연구','globe cabinet scroll lantern')]},
 {name:'공허의 틈',heights:[0,1,-1,0,2,0,3,0],floor:[0x9691a6,0x51495f,0xb1a7b7],accents:[0xa392b7,0xd3cbb8,0x91aaa9],mediums:'C:floating-rocks D:twisted-spire E:empty-throne F:mirror-wall',backdrops:'floating-rocks ruin shard',detail:'crack',clusters:[
  c('A','잔해','slab shard*4 ash'),c('B','속박','ruin*2 chain rings'),c('C','부유','rock*3 floating-shard*2'),c('D','기억','slab mask crystal'),c('E','왕좌','throne beam hourglass'),c('F','거울','mirror shard*4 stool')]},
 {name:'창조주의 정원',heights:[1,0,-1,2,0,-1,3,0],floor:[0xd9d8bc,0xa1b789,0xa2c4b4],accents:[0xc9bd89,0xd9b5bf,0xa5c9b8],mediums:'B:flower-arch D:crystal-spring E:seed-gazebo F:lotus-pond',backdrops:'golden-tree flower-arch crystal',detail:'leaf',clusters:[
  c('A','탄생','sprout*5 seed*3'),c('B','환영','arch flower*4 pebble*3'),c('C','수변','reed*3 rock*4 ripple'),c('D','수정','crystal*5 basin'),c('E','휴식','gazebo bench*2 bowl vine'),c('F','개화','lotus*3 leaf*4 petal*4')]},
];

export const zoneIndex=(letter:string)=>letter.charCodeAt(0)-65;
