import { EGGS, MONGLES, RARITIES, REGIONS, UPGRADES, TRAILS, BALANCE, TRAITS, rarityChances, type Upgrade } from "./data";
import {eggName,eggIcon} from "./stage-eggs";
import {type TraitId} from "./progression";
import type { GameState } from "./game";
import { formatNumber as num } from "./format";
export function panelHTML(tab: string, game: GameState) {
  if(tab==='traits')return `<span class="tag">EXPLORER GROWTH</span><h1>탐험가 특성</h1><p>LV.${game.level} · ${num(game.progression.xp)} / ${num(game.progression.requiredXP)} XP<br>5레벨마다 선택권 1개 · 남은 선택권 ${game.traitPoints}</p>${(Object.entries(TRAITS) as [TraitId,typeof TRAITS.sturdy][]).filter(([id])=>id!=='clock').map(([id,t])=>`<article class="stage-card"><h3>${t.name}</h3><p>${t.description} · ${game.progression.traits[id]??0}/${t.max}</p><button class="small-btn" data-trait="${id}" ${game.traitPoints<=0||(game.progression.traits[id]??0)>=t.max?'disabled':''}>선택하기</button></article>`).join('')}`;
  const owned=MONGLES.flatMap((_,i)=>game.save.mongles[i]>0?[i]:[]);
  if(tab==='pets')return `<span class="tag">MY LITTLE COMPANIONS</span><h1>함께할 펫</h1><p>최대 ${BALANCE.maxCompanions}마리 · 미장착 친구들은 농장에서 놀아요.</p><button data-tab="collection" class="secondary">도감 · 발견 보상 확인</button><div class="pet-slots">${Array.from({length:BALANCE.maxCompanions},(_,slot)=>{const id=game.save.active[slot];return id===undefined?'<div class="pet-slot empty">빈 자리</div>':`<button class="pet-slot" data-unequip="${id}" aria-label="${MONGLES[id].name} 해제"><img src="${import.meta.env.BASE_URL}models/pet-${id}.png" alt=""/><b>${MONGLES[id].name}</b><small>해제 ✕</small></button>`;}).join('')}</div><p>클릭 ×${game.clickMultiplier.toFixed(2)} · 오토 ×${game.autoMultiplier.toFixed(2)} · 스피드 ×${game.speedMultiplier.toFixed(2)}</p>${owned.length?owned.sort((a,b)=>Number(game.save.active.includes(b))-Number(game.save.active.includes(a))||MONGLES[b].tier-MONGLES[a].tier).map(id=>`<article class="friend"><img class="friend-face" src="${import.meta.env.BASE_URL}models/pet-${id}.png" alt="" loading="lazy"/><div><small>[${RARITIES[MONGLES[id].tier].name}] · 보유 ${num(game.save.mongles[id])}</small><h3>${MONGLES[id].name}</h3><b>${MONGLES[id].effect}</b></div><button class="small-btn" data-companion="${id}">${game.save.active.includes(id)?'착용 해제':'착용'}</button></article>`).join(''):'<p class="empty-state">아직 함께할 펫이 없어요.<br>알을 부화해 첫 친구를 만나 보세요.</p>'}`;
  if(tab==='store')return `<span class="tag">FARM TRADING POST</span><h1>농장 판매 스토어</h1><p>알이나 펫을 별가루로 바꿔요.<br>펫을 팔아도 도감 발견과 보상 기록은 남아요.</p><button data-tab="shop" class="secondary">트레일 상점으로</button><h2>보관 중인 알</h2>${game.save.eggs.length?game.save.eggs.map(e=>`<article class="sale-card"><img src="${eggIcon(e)}" alt=""/><div><b>${eggName(e)}</b><small>${EGGS[e.type].rarity} · HP ${num(Math.ceil(e.hp))}/${num(EGGS[e.type].hp)}</small></div><button class="small-btn" data-sell-egg="${e.id}">판매 +${num(game.eggSellPrice(e.type))}</button></article>`).join(''):'<p>판매할 알이 없어요.</p>'}<h2>보유 펫</h2>${owned.length?owned.map(id=>`<article class="sale-card"><img src="${import.meta.env.BASE_URL}models/pet-${id}.png" alt="" loading="lazy"/><div><b>${MONGLES[id].name}</b><small>${RARITIES[MONGLES[id].tier].name} · ${num(game.save.mongles[id])}마리${game.save.active.includes(id)?' · 착용 중':''}</small></div><button class="small-btn" data-sell-pet="${id}">1마리 판매 +${num(game.petSellPrice(id))}</button></article>`).join(''):'<p>판매할 펫이 없어요.</p>'}`;
  const region=Number(document.getElementById("panel")?.dataset.region??0);
  const regionPets=MONGLES.flatMap((m,i)=>m.region===region?[i]:[]);
  const complete=regionPets.every(i=>game.hasDiscoveredPet(i));
  const collectionHeader=`<div class="region-tabs">${REGIONS.map((r,i)=>`<button data-region="${i}" class="${region===i?"active":""}">${r.name}</button>`).join("")}</div><div class="collection-reward"><b>${REGIONS[region].name} ${regionPets.filter(i=>game.hasDiscoveredPet(i)).length}/20</b><button class="small-btn" data-claim-region="${region}" ${!complete||game.save.claimedRegions?.includes(region)?"disabled":""}>${game.save.claimedRegions?.includes(region)?"지역 보상 수령 완료":`완성 보상 ✦ ${num(BALANCE.regionCollectionRewards[region])}`}</button><button class="small-btn" id="claim-all" ${MONGLES.some((_,i)=>!game.hasDiscoveredPet(i))||game.save.claimedCollection?"disabled":""}>${game.save.claimedCollection?"전체 보상 수령 완료":`100종 완성 ✦ ${num(BALANCE.fullCollectionReward)}`}</button></div>`;
  if (tab === "collection") return `<span class="tag">FARM FIELD GUIDE</span><h1>달잠 농장 도감</h1><p>처음 만난 친구만 모습을 알려줘요. 보유 펫은 농장에서 놀아요.</p><div class="collection-count">${MONGLES.filter((_,i)=>game.hasDiscoveredPet(i)).length}<small> / ${MONGLES.length} 발견 · 농장 최대 ${BALANCE.farmPetsVisible}종씩 순환</small></div><details class="rarity-guide"><summary>지역별 알 확률 · 크기</summary><table><thead><tr><th>등급</th><th>크기</th>${REGIONS.map(r=>`<th>${r.name}</th>`).join("")}</tr></thead><tbody>${RARITIES.map((r,i)=>`<tr><td>${r.name}</td><td>${r.size}</td>${REGIONS.map((_,j)=>`<td>${rarityChances(j)[i].toFixed(2)}%</td>`).join("")}</tr>`).join("")}</tbody></table></details>${collectionHeader}${MONGLES.map((m,i)=>m.region!==region?"":game.hasDiscoveredPet(i)?`<article class="friend"><button class="friend-face claim-pet" data-claim-pet="${i}" aria-label="${m.name} discovery reward"><img src="${import.meta.env.BASE_URL}models/pet-${i}.png" alt="${m.name}" loading="lazy" /><small>${game.save.claimedPets?.includes(i)?"OK":`+${num(game.discoveryReward(i))}`}</small></button><div><small>NO.${String(i+1).padStart(3,"0")} · ${RARITIES[m.tier].name} · ${m.grid}³</small><h3>${m.name}</h3><p>${m.description}</p><b>${m.effect}</b></div><span class="owned">보유 ${num(game.save.mongles[i])}마리</span></article>`:`<article class="friend locked"><div class="friend-face unknown" aria-label="미발견">?</div><div><small>NO.${String(i+1).padStart(3,"0")}</small><h3>???</h3><p>아직 만나지 못한 친구</p><b>능력 ???</b></div></article>`).join("")}`;
  if(tab === "shop") return `<span class="tag">DANDELION TRAIL CO.</span><h1>바람 꼬리 상점</h1><p>운동으로 기른 속도에 배수를 더해요.<br>영구 소유 · 한 종류 장착 · 별가루로만 구매</p><button id="virtual-ad" class="secondary">가상 광고 · +${num(BALANCE.virtualAdReward)}</button><div class="shop-speed">이동속도 <b>${num(game.speed,2)}</b></div>${TRAILS.map((t,i)=>`<article class="trail-card" style="--trail:${t.color}"><img src="${import.meta.env.BASE_URL}models/${t.model}.png" alt="" /><div><h3>${t.name}</h3><strong>×${t.multiplier.toFixed(2)}</strong><p>${i===0?"가벼운 첫 발걸음": ["","발끝에 흩날리는 꽃가루","따라오는 초록 반딧불","보랏빛 별조각의 긴 꼬리"][i]}</p></div><button class="small-btn" data-trail="${i}" ${!(game.save.trails??[0]).includes(i)&&game.save.dust<t.cost?"disabled":""}>${game.save.equippedTrail===i?"착용 중":(game.save.trails??[0]).includes(i)?"착용":`✦ ${num(t.cost)}`}</button></article>`).join("")}`;
  if(tab === "upgrade") return `<span class="tag">FARM WORKSHOP</span><h1>조금 더 멀리, 조금 더 빠르게</h1><p>농장 오른쪽 러닝머신에 다가가 운동을 시작하세요.</p><div class="training-stats">운동으로 얻은 속도 <b>+${num(game.trainingSpeedBonus,3)}</b><br>운동 1초당 <b>+${num(game.effectiveTrainingRate,3)}</b></div>${(Object.entries(UPGRADES) as [Upgrade,typeof UPGRADES.speed][]).filter(([k])=>k!=='time').map(([k,u])=>`<article class="upgrade"><span class="upgrade-icon"><img src="${import.meta.env.BASE_URL}models/${({speed:"alkong",carry:"pack",tap:"hammer",damage:"pet-9",rate:"egg-3",time:"compass",training:"gym",health:"pack"})[k]}.png" alt="" /></span><div><small>LV.${game.save.upgrades[k]}</small><h3>${u.name}</h3><p>${u.description}</p></div><button data-upgrade="${k}" ${game.save.dust<game.cost(k)||game.save.upgrades[k]>=BALANCE.maxUpgrade?"disabled":""}>${game.save.upgrades[k]>=BALANCE.maxUpgrade?"최대":"✦ "+num(game.cost(k))}</button></article>`).join("")}`;
  return "";
}
