import { EGGS, MONGLES, RARITIES, REGIONS, UPGRADES, TRAILS, BALANCE, TRAITS, STAGE_COLLECTION_REWARDS, petIcon, rarityChances, type Upgrade } from "./data";
import {STAGES} from "./stage-data";
import {eggName,eggIcon} from "./stage-eggs";
import {type TraitId} from "./progression";
import type { GameState } from "./game";
import { formatNumber as num } from "./format";
export function panelHTML(tab: string, game: GameState) {
  if(tab==='traits')return `<span class="tag">EXPLORER GROWTH</span><h1>탐험가 특성</h1><p>LV.${game.level} · ${num(game.progression.xp)} / ${num(game.progression.requiredXP)} XP<br>5레벨마다 선택권 1개 · 남은 선택권 ${game.traitPoints}</p>${(Object.entries(TRAITS) as [TraitId,typeof TRAITS.sturdy][]).filter(([id])=>id!=='clock').map(([id,t])=>`<article class="stage-card"><h3>${t.name}</h3><p>${t.description} · ${game.progression.traits[id]??0}/${t.max}</p><button class="small-btn" data-trait="${id}" ${game.traitPoints<=0||(game.progression.traits[id]??0)>=t.max?'disabled':''}>선택하기</button></article>`).join('')}`;
  const owned=MONGLES.flatMap((_,i)=>game.save.mongles[i]>0?[i]:[]);
  if(tab==='pets')return `<span class="tag">MY LITTLE COMPANIONS</span><h1>함께할 펫</h1><p>최대 ${BALANCE.maxCompanions}마리 · 미장착 친구들은 농장에서 놀아요.</p><button data-tab="collection" class="secondary">도감 · 발견 보상 확인</button><div class="pet-slots">${Array.from({length:BALANCE.maxCompanions},(_,slot)=>{const id=game.save.active[slot];return id===undefined?'<div class="pet-slot empty">빈 자리</div>':`<button class="pet-slot" data-unequip="${id}" aria-label="${MONGLES[id].name} 해제"><img src="${petIcon(id)}" alt=""/><b>${MONGLES[id].name}</b><small>해제 ✕</small></button>`;}).join('')}</div><p>착용 펫 수익 · ${BALANCE.petIncomeSeconds}초마다 별가루 +${num(game.petIncomePerCycle)}<br><small>플레이 중 자동 지급 · 등급 기본 수익 × 출처 스테이지 배수</small></p><p>클릭 ×${game.clickMultiplier.toFixed(2)} · 오토 ×${game.autoMultiplier.toFixed(2)} · 스피드 ×${game.speedMultiplier.toFixed(2)}</p>${owned.length?owned.sort((a,b)=>Number(game.save.active.includes(b))-Number(game.save.active.includes(a))||MONGLES[b].tier-MONGLES[a].tier).map(id=>`<article class="friend"><img class="friend-face" src="${petIcon(id)}" alt="" loading="lazy"/><div><small>[${RARITIES[MONGLES[id].tier].name}] · 보유 ${num(game.save.mongles[id])}</small><h3>${MONGLES[id].name}</h3><b>${MONGLES[id].effect}</b><p>${MONGLES[id].stageId?`STAGE ${MONGLES[id].stageId}`:`이전 도감 · ${REGIONS[MONGLES[id].region].name}`} · 수익 ×${game.petIncomeStageMultiplier(id)}<br>별가루 +${num(game.petIncomeAmount(id))} / ${BALANCE.petIncomeSeconds}초</p></div><button class="small-btn" data-companion="${id}">${game.save.active.includes(id)?'착용 해제':'착용'}</button></article>`).join(''):'<p class="empty-state">아직 함께할 펫이 없어요.<br>알을 부화해 첫 친구를 만나 보세요.</p>'}`;
  if(tab==='store')return `<span class="tag">FARM TRADING POST</span><h1>농장 판매 스토어</h1><p>알이나 펫을 별가루로 바꿔요.<br>펫을 팔아도 도감 발견과 보상 기록은 남아요.</p><button data-tab="shop" class="secondary">트레일 상점으로</button><h2>보관 중인 알</h2>${game.save.eggs.length?game.save.eggs.map(e=>`<article class="sale-card"><img src="${eggIcon(e)}" alt=""/><div><b>${eggName(e)}</b><small>${EGGS[e.type].rarity} · HP ${num(Math.ceil(e.hp))}/${num(EGGS[e.type].hp)}</small></div><button class="small-btn" data-sell-egg="${e.id}">판매 +${num(game.eggSellPrice(e.type))}</button></article>`).join(''):'<p>판매할 알이 없어요.</p>'}<h2>보유 펫</h2>${owned.length?owned.map(id=>`<article class="sale-card"><img src="${petIcon(id)}" alt="" loading="lazy"/><div><b>${MONGLES[id].name}</b><small>${RARITIES[MONGLES[id].tier].name} · ${num(game.save.mongles[id])}마리${game.save.active.includes(id)?' · 착용 중':''}</small></div><button class="small-btn" data-sell-pet="${id}">1마리 판매 +${num(game.petSellPrice(id))}</button></article>`).join(''):'<p>판매할 펫이 없어요.</p>'}`;
  if(tab==='collection'){
    const raw=Number(document.getElementById('panel')?.dataset.collectionStage??game.stage.id);
    const stage=Number.isInteger(raw)&&raw>=0&&raw<=20?raw:1;
    const legacy=stage===0;
    const region=Math.max(0,Math.min(4,Number(document.getElementById('panel')?.dataset.region??0)||0));
    const members=MONGLES.flatMap((m,i)=>(legacy?m.stageId===0&&m.region===region:m.stageId===stage)?[i]:[]);
    const catalog=MONGLES.flatMap((m,i)=>(legacy?m.stageId===0:m.stageId>0)?[i]:[]);
    const count=members.filter(i=>game.hasDiscoveredPet(i)).length;
    const claimed=legacy?game.save.claimedRegions?.includes(region):game.save.claimedStages?.includes(stage);
    const fullClaimed=legacy?game.save.claimedCollection:game.save.claimedStageCollection;
    const title=legacy?`이전 도감 · ${REGIONS[region].name}`:`${stage}. ${STAGES[stage-1].name}`;
    const reward=legacy?BALANCE.regionCollectionRewards[region]:STAGE_COLLECTION_REWARDS[stage-1];
    const chances=rarityChances(legacy?region:Math.floor((stage-1)/4));
    return `<span class="tag">STAGE FIELD GUIDE</span><h1>스테이지 펫 도감</h1><p>20개 스테이지마다 전용 펫 10종. 가져온 알의 출처 스테이지에서만 태어나는 친구들이에요.</p>
      <div class="collection-count">${catalog.filter(i=>game.hasDiscoveredPet(i)).length}<small> / ${catalog.length} 발견${legacy?' · 이전 수집 기록':' · 스테이지 전용 펫'}</small></div>
      <details class="stage-categories"><summary>${title} · 카테고리 변경</summary><div class="stage-category-grid">${STAGES.map(s=>{const found=MONGLES.filter((m,i)=>m.stageId===s.id&&game.hasDiscoveredPet(i)).length;return `<button data-collection-stage="${s.id}" class="${stage===s.id?'active':''}" aria-pressed="${stage===s.id}"><b>${s.id}. ${s.name}</b><small>${found}/10</small></button>`;}).join('')}<button data-collection-stage="0" class="${legacy?'active':''}">이전 도감 · 기존 100종</button></div></details>
      ${legacy?`<div class="region-tabs">${REGIONS.map((r,i)=>`<button data-region="${i}" class="${region===i?'active':''}">${r.name}</button>`).join('')}</div>`:''}
      <h2>${title}</h2><div class="collection-reward"><b>${count}/${members.length} 발견</b><button class="small-btn" ${legacy?'data-claim-region':'data-claim-stage'}="${legacy?region:stage}" ${count!==members.length||claimed?'disabled':''}>${claimed?'완성 보상 수령 완료':`완성 보상 ✦ ${num(reward)}`}</button><button class="small-btn" id="${legacy?'claim-all':'claim-stage-all'}" ${fullClaimed||catalog.some(i=>!game.hasDiscoveredPet(i))?'disabled':''}>${fullClaimed?'전체 보상 수령 완료':`${catalog.length}종 완성 ✦ ${num(BALANCE.fullCollectionReward)}`}</button></div>
      <details class="rarity-guide"><summary>이 스테이지의 등급 확률</summary><p>알 등급이 펫 등급을 정해요. 같은 등급의 전용 펫은 동일 확률로 태어나요.</p><table><thead><tr><th>등급</th><th>알 확률</th><th>펫 종류</th></tr></thead><tbody>${RARITIES.map((r,tier)=>`<tr><td>${r.name}</td><td>${chances[tier].toFixed(2)}%</td><td>${members.filter(i=>MONGLES[i].tier===tier).length}종</td></tr>`).join('')}</tbody></table></details>
      ${members.map((i,slot)=>{const m=MONGLES[i];return game.hasDiscoveredPet(i)?`<article class="friend"><button class="friend-face claim-pet" data-claim-pet="${i}" aria-label="${m.name} 발견 보상"><img src="${petIcon(i)}" alt="${m.name}" loading="lazy"/><small>${game.save.claimedPets?.includes(i)?'OK':`+${num(game.discoveryReward(i))}`}</small></button><div><small>${legacy?'이전':`STAGE ${stage}`} · NO.${String(slot+1).padStart(2,'0')} · ${RARITIES[m.tier].name} · ${m.grid}³</small><h3>${m.name}</h3><p>${m.description}</p><b>${m.effect}</b></div><span class="owned">보유 ${num(game.save.mongles[i])}마리</span></article>`:`<article class="friend locked"><div class="friend-face unknown" aria-label="미발견">?</div><div><small>NO.${String(slot+1).padStart(2,'0')} · ${RARITIES[m.tier].name}</small><h3>???</h3><p>${legacy?'이전 지역의 알에서 만나는 친구':`${STAGES[stage-1].name}의 전용 친구`}</p></div></article>`;}).join('')}`;
  }
  if(tab === "shop") return `<span class="tag">DANDELION TRAIL CO.</span><h1>바람 꼬리 상점</h1><p>운동으로 기른 속도에 배수를 더해요.<br>영구 소유 · 한 종류 장착 · 별가루로만 구매</p><button id="virtual-ad" class="secondary">가상 광고 · +${num(BALANCE.virtualAdReward)}</button><div class="shop-speed">이동속도 <b>${num(game.speed,2)}</b></div>${TRAILS.map((t,i)=>`<article class="trail-card" style="--trail:${t.color}"><img src="${import.meta.env.BASE_URL}models/${t.model}.png" alt="" /><div><h3>${t.name}</h3><strong>×${t.multiplier.toFixed(2)}</strong><p>${i===0?"가벼운 첫 발걸음": ["","발끝에 흩날리는 꽃가루","따라오는 초록 반딧불","보랏빛 별조각의 긴 꼬리"][i]}</p></div><button class="small-btn" data-trail="${i}" ${!(game.save.trails??[0]).includes(i)&&game.save.dust<t.cost?"disabled":""}>${game.save.equippedTrail===i?"착용 중":(game.save.trails??[0]).includes(i)?"착용":`✦ ${num(t.cost)}`}</button></article>`).join("")}`;
  if(tab === "upgrade") return `<span class="tag">FARM WORKSHOP</span><h1>조금 더 멀리, 조금 더 빠르게</h1><p>기지의 운동하기 버튼을 누르면 트레드밀에서 바로 운동해요.</p><div class="training-stats">운동으로 얻은 속도 <b>+${num(game.trainingSpeedBonus,3)}</b><br>운동 1초당 <b>+${num(game.effectiveTrainingRate,3)}</b></div>${(Object.entries(UPGRADES) as [Upgrade,typeof UPGRADES.speed][]).filter(([k])=>k!=='time').map(([k,u])=>`<article class="upgrade"><span class="upgrade-icon"><img src="${import.meta.env.BASE_URL}models/${({speed:"alkong",carry:"pack",tap:"hammer",damage:"pet-9",rate:"egg-3",time:"compass",training:"gym",health:"pack"})[k]}.png" alt="" /></span><div><small>LV.${game.save.upgrades[k]}</small><h3>${u.name}</h3><p>${u.description}</p></div><button data-upgrade="${k}" ${game.save.dust<game.cost(k)||game.save.upgrades[k]>=BALANCE.maxUpgrade?"disabled":""}>${game.save.upgrades[k]>=BALANCE.maxUpgrade?"최대":"✦ "+num(game.cost(k))}</button></article>`).join("")}`;
  return "";
}
