import {eggMaxHp,eggWeightLabel} from './data';
import {weeklyPanel} from './weekly-ui';
import {compare} from './money';
import { EGGS, MONGLES, RARITIES, REGIONS, UPGRADES, TRAILS, BALANCE, STAGE_COLLECTION_REWARDS, petIcon, rarityChances, type Upgrade } from "./data";
import {STAGES} from "./stage-data";
import {eggName,eggIcon} from "./stage-eggs";
import type { GameState } from "./game";
import { formatNumber as num } from "./format";
import {uiIcon} from './ui-icons';
import {petAbilities,petIncomeBadge} from './pet-stats';
function collectionCard(i:number,slot:number,game:GameState){
 const m=MONGLES[i],found=game.hasDiscoveredPet(i),claimed=game.save.claimedPets?.includes(i);
 if((i>=300&&i<320)&&!found)return `<article class="pet-catalog-card secret-pet"><div class="pet-portrait"><img src="${import.meta.env.BASE_URL}models/stage-previews/pet-${i}-silhouette.png" alt="숨겨진 드래곤 실루엣" loading="lazy"/></div><small>SECRET DRAGON</small><h3>숨겨진 수호룡</h3><p>${STAGES[m.stageId-1].name} · 전용 알 ${(BALANCE.secretDragonEggChance*100).toFixed(2)}%</p></article>`;
 return `<article class="pet-catalog-card ${found?'':'locked'} ${(i>=300&&i<320)?'secret-pet':''}">${found?`<button class="pet-portrait" data-pet-view="${i}" aria-label="${m.name} 크게 보기"><img src="${petIcon(i)}" alt="${m.name}" loading="lazy"/></button>`:'<div class="pet-portrait unknown" aria-label="미발견">?</div>'}<small>NO.${String(slot+1).padStart(2,'0')} · ${RARITIES[m.tier].name}</small><h3>${found?m.name:'???'}</h3>${found?`<div class="stat-badges">${petAbilities(m)}</div><details class="pet-details"><summary>상세</summary><p>${m.description}<br>${m.effect}</p></details><small>보유 ${num(game.save.mongles[i])}</small><button class="small-btn" data-claim-pet="${i}" ${claimed?'disabled':''}>${claimed?'보상 수령 완료':`+${num(game.discoveryReward(i))}`}</button>`:''}</article>`;
}

export function panelHTML(tab: string, game: GameState) {
  if(tab==='weekly')return weeklyPanel(game);
  const owned=MONGLES.flatMap((_,i)=>game.save.mongles[i]>0?[i]:[]);
  if(tab==='pets')return `<h1>함께할 펫</h1><div class="pet-summary stat-badges">${petAbilities(game,true)}${petIncomeBadge(game.petIncomePerCycle,BALANCE.petIncomeSeconds)}</div>
    <details class="pet-help"><summary>아이콘 안내</summary><div class="stat-legend">${uiIcon('tap')} 터치 피해 ${uiIcon('auto')} 자동 피해 ${uiIcon('speed')} 이동 속도 ${uiIcon('dust')} 별가루 수익</div><p>같은 펫도 보유 수량만큼, 최대 ${BALANCE.maxCompanions}마리까지 착용해요. 착용한 펫은 따라오고 나머지는 내 울타리에서 놀아요.</p><p>능력 배율의 ×1을 초과한 보너스를 합산해요. 수익은 오프라인에서도 100% 누적돼요 (최대 48시간).</p></details>
    <button data-tab="collection" class="secondary">도감</button><div class="pet-slots">${Array.from({length:BALANCE.maxCompanions},(_,slot)=>{const id=game.save.active[slot];return id===undefined?'<div class="pet-slot empty">빈 자리</div>':`<button class="pet-slot" data-unequip="${id}" aria-label="${MONGLES[id].name} 한 마리 해제"><img src="${petIcon(id)}" alt=""/><b>${MONGLES[id].name}</b><small>한 마리 해제 ×</small></button>`;}).join('')}</div>
    ${owned.length?owned.sort((a,b)=>Number(game.save.active.includes(b))-Number(game.save.active.includes(a))||MONGLES[b].sourceEggHp-MONGLES[a].sourceEggHp||MONGLES[b].tier-MONGLES[a].tier).map(id=>{
      const equipped=game.equippedCount(id),remaining=game.save.mongles[id]-equipped;
      return `<article class="friend"><button class="friend-preview" data-pet-view="${id}" aria-label="${MONGLES[id].name}"><img src="${petIcon(id)}" alt="" loading="lazy"/></button><div><small>${RARITIES[MONGLES[id].tier].name}${MONGLES[id].stageId?` · STAGE ${MONGLES[id].stageId}`:""} · 보유 ${num(game.save.mongles[id])}마리 · 착용 ${equipped}마리</small><h3>${MONGLES[id].name}</h3><div class="stat-badges">${petAbilities(MONGLES[id])}${petIncomeBadge(game.petIncomeAmount(id),BALANCE.petIncomeSeconds)}</div><details class="pet-details"><summary>상세</summary><p>${MONGLES[id].effect}<br>${MONGLES[id].stageId?`STAGE ${MONGLES[id].stageId}`:REGIONS[MONGLES[id].region].name} · 수익 ×${game.petIncomeStageMultiplier(id)}</p></details></div><div class="pet-actions"><button class="small-btn" data-companion="${id}" ${!remaining||game.save.active.length>=BALANCE.maxCompanions?'disabled':''}>${!remaining?'모두 착용 중':equipped?'한 마리 더 착용':'착용'}</button><button class="small-btn" data-sell-pet="${id}">1마리 판매 +${num(game.petSellPrice(id))}</button></div></article>`;
    }).join(''):'<p class="empty-state">알을 부화해 첫 친구를 만나 보세요.</p>'}`;
  if(tab==='store')return `<span class="tag">FARM TRADING POST</span><h1>농장 판매 스토어</h1><p>알이나 펫을 별가루로 바꿔요.<br>펫을 팔아도 도감 발견과 보상 기록은 남아요.</p><button data-tab="shop" class="secondary">트레일 상점으로</button><h2>보관 중인 알</h2>${game.save.eggs.length?game.save.eggs.map(e=>`<article class="sale-card"><img src="${eggIcon(e)}" alt=""/><div><b>${eggName(e)}</b><small>${EGGS[e.type].rarity} · HP ${num(Math.ceil(e.hp))}/${num(eggMaxHp(e))}</small><small>${eggWeightLabel(e.type,game.save.upgrades.carry)}</small></div><button class="small-btn" data-sell-egg="${e.id}">판매 +${num(game.eggSellPrice(e.type))}</button></article>`).join(''):'<p>판매할 알이 없어요.</p>'}<h2>보유 펫</h2>${owned.length?owned.map(id=>`<article class="sale-card"><img src="${petIcon(id)}" alt="" loading="lazy"/><div><b>${MONGLES[id].name}</b><small>${RARITIES[MONGLES[id].tier].name}${MONGLES[id].stageId?` · STAGE ${MONGLES[id].stageId}`:""} · ${num(game.save.mongles[id])}마리${game.save.active.includes(id)?' · 착용 중':''}</small></div><button class="small-btn" data-sell-pet="${id}">1마리 판매 +${num(game.petSellPrice(id))}</button></article>`).join(''):'<p>판매할 펫이 없어요.</p>'}`;
  if(tab==='collection'){
    const raw=Number(document.getElementById('panel')?.dataset.collectionStage??game.stage.id);
    const stage=Number.isInteger(raw)&&raw>=1&&raw<=20?raw:game.stage.id;
    const legacy=stage===0;
    const region=Math.max(0,Math.min(4,Number(document.getElementById('panel')?.dataset.region??0)||0));
    const members=MONGLES.flatMap((m,i)=>(legacy?i<100&&m.stageId===0&&m.region===region:m.stageId===stage)?[i]:[]);
    const catalog=MONGLES.flatMap((m,i)=>(legacy?i<100&&m.stageId===0:m.stageId>0)?[i]:[]);
    const count=members.filter(i=>game.hasDiscoveredPet(i)).length;
    const claimed=legacy?game.save.claimedRegions?.includes(region):game.save.claimedStages?.includes(stage);
    const fullClaimed=legacy?game.save.claimedCollection:game.save.claimedStageCollection;
    const title=legacy?`이전 도감 · ${REGIONS[region].name}`:`${stage}. ${STAGES[stage-1].name}`;
    const reward=legacy?BALANCE.regionCollectionRewards[region]:STAGE_COLLECTION_REWARDS[stage-1];
    const chances=rarityChances(legacy?region:Math.floor((stage-1)/4)).map((chance,tier)=>legacy?chance:chance*(1-BALANCE.secretDragonEggChance)+(tier===6?BALANCE.secretDragonEggChance*100:0));
    return `<h1>펫 도감</h1><button data-tab="weekly">🎁 주간 보상</button>${collectionCard(320,320,game)}
      <div class="collection-count">${catalog.filter(i=>game.hasDiscoveredPet(i)).length}<small> / ${catalog.length} 발견${legacy?' · 이전 수집 기록':' · 스테이지 전용 펫'}</small></div>
      <details class="stage-categories"><summary>${title} · 카테고리 변경</summary><div class="stage-category-grid">${STAGES.map(s=>{const found=MONGLES.filter((m,i)=>m.stageId===s.id&&game.hasDiscoveredPet(i)).length;return `<button data-collection-stage="${s.id}" class="${stage===s.id?'active':''}" aria-pressed="${stage===s.id}"><b>${s.id}. ${s.name}</b><small>${found}/11</small></button>`;}).join('')}</div></details>
      ${legacy?`<div class="region-tabs">${REGIONS.map((r,i)=>`<button data-region="${i}" class="${region===i?'active':''}">${r.name}</button>`).join('')}</div>`:''}
      <details class="collection-tools"><summary>${count}/${members.length} 발견 · 보상 / 확률</summary><div class="collection-reward"><b>${count}/${members.length} 발견</b><button class="small-btn" ${legacy?'data-claim-region':'data-claim-stage'}="${legacy?region:stage}" ${count!==members.length||claimed?'disabled':''}>${claimed?'완성 보상 수령 완료':`완성 보상 별가루 ${num(reward)}`}</button><button class="small-btn" id="${legacy?'claim-all':'claim-stage-all'}" ${fullClaimed||catalog.some(i=>!game.hasDiscoveredPet(i))?'disabled':''}>${fullClaimed?'전체 보상 수령 완료':`${catalog.length}종 완성 별가루 ${num(BALANCE.fullCollectionReward)}`}</button></div>
      <details class="rarity-guide"><summary>이 스테이지의 등급 확률</summary><p>알 등급이 펫 등급을 정해요. 같은 등급의 전용 펫은 동일 확률로 태어나요.</p><table><thead><tr><th>등급</th><th>알 확률</th><th>펫 종류</th></tr></thead><tbody>${RARITIES.map((r,tier)=>`<tr><td>${r.name}</td><td>${chances[tier].toFixed(2)}%</td><td>${members.filter(i=>MONGLES[i].tier===tier).length}종</td></tr>`).join('')}</tbody></table></details>
      </details><div class="pet-catalog-grid">${members.map((i,slot)=>collectionCard(i,slot,game)).join('')}</div>`;
  }
  if(tab === "shop") return `<span class="tag">DANDELION TRAIL CO.</span><h1>바람 꼬리 상점</h1><p>운동으로 기른 속도에 배수를 더해요.<br>영구 소유 · 한 종류 장착 · 별가루로만 구매</p><button id="virtual-ad" class="secondary">가상 광고 · +${num(BALANCE.virtualAdReward)}</button><div class="shop-speed">이동속도 <b>${num(game.speed,2)}</b></div>${TRAILS.map((t,i)=>`<article class="trail-card" style="--trail:${t.color}"><img src="${import.meta.env.BASE_URL}models/${t.model}.png" alt="" /><div><h3>${t.name}</h3><strong>×${t.multiplier.toFixed(2)}</strong><p>${i===0?"가벼운 첫 발걸음": ["","발끝에 흩날리는 꽃가루","따라오는 초록 반딧불","보랏빛 별조각의 긴 꼬리"][i]}</p></div><button class="small-btn" data-trail="${i}" ${!(game.save.trails??[0]).includes(i)&&compare(game.save.dust,t.cost)<0?"disabled":""}>${game.save.equippedTrail===i?"착용 중":(game.save.trails??[0]).includes(i)?"착용":`별가루 ${num(t.cost)}`}</button></article>`).join("")}`;
  if(tab === "upgrade") return `<span class="tag">FARM WORKSHOP</span><h1>조금 더 멀리, 조금 더 빠르게</h1><p>기지의 운동하기 버튼을 누르면 트레드밀에서 바로 운동해요.</p><div class="training-stats">운동으로 얻은 속도 <b>+${num(game.trainingSpeedBonus,3)}</b><br>운동 1초당 <b>+${num(game.effectiveTrainingRate,3)}</b></div>${(Object.entries(UPGRADES) as [Upgrade,typeof UPGRADES.speed][]).filter(([k])=>k!=='time').map(([k,u])=>`<article class="upgrade"><span class="upgrade-icon"><img src="${import.meta.env.BASE_URL}models/${({speed:"alkong",carry:"pack",tap:"hammer",damage:"pet-9",rate:"egg-3",time:"compass",training:"gym",health:"pack"})[k]}.png" alt="" /></span><div><small>LV.${game.save.upgrades[k]}</small><h3>${u.name}</h3><p>${u.description}</p></div><button data-upgrade="${k}" ${compare(game.save.dust,game.cost(k))<0||game.save.upgrades[k]>=BALANCE.maxUpgrade?"disabled":""}>${game.save.upgrades[k]>=BALANCE.maxUpgrade?"최대":"별가루 "+num(game.cost(k))}</button></article>`).join("")}`;
  return "";
}
