// Generated by scripts/generate_stage_pets.py; legacy IDs 0–99 stay intact.
export const STAGE_PET_ROWS = [
  {
    "name": "새순 뽀미",
    "description": "몽글 초원의 새순 뽀미. 머리 위 싹을 돌보며 작은 빛을 나눠 줍니다.",
    "stageId": 1,
    "slot": 0,
    "tier": 0,
    "color": "#c9dda0",
    "shape": "plant"
  },
  {
    "name": "클로버 토토",
    "description": "몽글 초원의 클로버 토토. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 1,
    "slot": 1,
    "tier": 0,
    "color": "#c9dda0",
    "shape": "rabbit"
  },
  {
    "name": "민들레 삐삐",
    "description": "몽글 초원의 민들레 삐삐. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 1,
    "slot": 2,
    "tier": 1,
    "color": "#c9dda0",
    "shape": "bird"
  },
  {
    "name": "딸기 볼쥐",
    "description": "몽글 초원의 딸기 볼쥐. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 1,
    "slot": 3,
    "tier": 1,
    "color": "#c9dda0",
    "shape": "quadruped"
  },
  {
    "name": "도토리 꼬북",
    "description": "몽글 초원의 도토리 꼬북. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 1,
    "slot": 4,
    "tier": 2,
    "color": "#c9dda0",
    "shape": "shell"
  },
  {
    "name": "풍차 병아리",
    "description": "몽글 초원의 풍차 병아리. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 1,
    "slot": 5,
    "tier": 2,
    "color": "#c9dda0",
    "shape": "bird"
  },
  {
    "name": "꿀단지 곰곰",
    "description": "몽글 초원의 꿀단지 곰곰. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 1,
    "slot": 6,
    "tier": 3,
    "color": "#c9dda0",
    "shape": "quadruped"
  },
  {
    "name": "꽃갈기 사자",
    "description": "몽글 초원의 꽃갈기 사자. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 1,
    "slot": 7,
    "tier": 4,
    "color": "#c9dda0",
    "shape": "quadruped"
  },
  {
    "name": "무지개 나비룡",
    "description": "몽글 초원의 무지개 나비룡. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 1,
    "slot": 8,
    "tier": 5,
    "color": "#c9dda0",
    "shape": "dragon"
  },
  {
    "name": "사계절 정원사슴",
    "description": "몽글 초원의 사계절 정원사슴. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 1,
    "slot": 9,
    "tier": 6,
    "color": "#c9dda0",
    "shape": "quadruped"
  },
  {
    "name": "단추 삐봇",
    "description": "장난감 왕국의 단추 삐봇. 관절과 장치를 달그락거리며 부지런히 따라옵니다.",
    "stageId": 2,
    "slot": 0,
    "tier": 0,
    "color": "#ddb28c",
    "shape": "machine"
  },
  {
    "name": "블록 멍멍",
    "description": "장난감 왕국의 블록 멍멍. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 2,
    "slot": 1,
    "tier": 0,
    "color": "#ddb28c",
    "shape": "quadruped"
  },
  {
    "name": "종이비행 참새",
    "description": "장난감 왕국의 종이비행 참새. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 2,
    "slot": 2,
    "tier": 1,
    "color": "#ddb28c",
    "shape": "bird"
  },
  {
    "name": "오뚝이 통통",
    "description": "장난감 왕국의 오뚝이 통통. 발 없이 둥실 떠다니며 잠든 추억을 깨웁니다.",
    "stageId": 2,
    "slot": 3,
    "tier": 1,
    "color": "#ddb28c",
    "shape": "spirit"
  },
  {
    "name": "실타래 토끼",
    "description": "장난감 왕국의 실타래 토끼. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 2,
    "slot": 4,
    "tier": 2,
    "color": "#ddb28c",
    "shape": "rabbit"
  },
  {
    "name": "주사위 거북",
    "description": "장난감 왕국의 주사위 거북. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 2,
    "slot": 5,
    "tier": 2,
    "color": "#ddb28c",
    "shape": "shell"
  },
  {
    "name": "팽이 발레리나",
    "description": "장난감 왕국의 팽이 발레리나. 발 없이 둥실 떠다니며 잠든 추억을 깨웁니다.",
    "stageId": 2,
    "slot": 6,
    "tier": 3,
    "color": "#ddb28c",
    "shape": "spirit"
  },
  {
    "name": "기관차 코끼리",
    "description": "장난감 왕국의 기관차 코끼리. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 2,
    "slot": 7,
    "tier": 4,
    "color": "#ddb28c",
    "shape": "quadruped"
  },
  {
    "name": "인형극 꼭두룡",
    "description": "장난감 왕국의 인형극 꼭두룡. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 2,
    "slot": 8,
    "tier": 5,
    "color": "#ddb28c",
    "shape": "dragon"
  },
  {
    "name": "왕관 태엽곰",
    "description": "장난감 왕국의 왕관 태엽곰. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 2,
    "slot": 9,
    "tier": 6,
    "color": "#ddb28c",
    "shape": "quadruped"
  },
  {
    "name": "거품 방울어",
    "description": "얕은 산호 바다의 거품 방울어. 꼬리지느러미를 흔들며 공중을 헤엄칩니다.",
    "stageId": 3,
    "slot": 0,
    "tier": 0,
    "color": "#8ed8cd",
    "shape": "fish"
  },
  {
    "name": "소라 소곤",
    "description": "얕은 산호 바다의 소라 소곤. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 3,
    "slot": 1,
    "tier": 0,
    "color": "#8ed8cd",
    "shape": "shell"
  },
  {
    "name": "산호 집게",
    "description": "얕은 산호 바다의 산호 집게. 여러 갈래 팔로 호기심 가는 물건을 만져 봅니다.",
    "stageId": 3,
    "slot": 2,
    "tier": 1,
    "color": "#8ed8cd",
    "shape": "tentacle"
  },
  {
    "name": "해초 해마",
    "description": "얕은 산호 바다의 해초 해마. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 3,
    "slot": 3,
    "tier": 1,
    "color": "#8ed8cd",
    "shape": "dragon"
  },
  {
    "name": "진주 조개",
    "description": "얕은 산호 바다의 진주 조개. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 3,
    "slot": 4,
    "tier": 2,
    "color": "#8ed8cd",
    "shape": "shell"
  },
  {
    "name": "줄무늬 삐에로어",
    "description": "얕은 산호 바다의 줄무늬 삐에로어. 꼬리지느러미를 흔들며 공중을 헤엄칩니다.",
    "stageId": 3,
    "slot": 5,
    "tier": 2,
    "color": "#8ed8cd",
    "shape": "fish"
  },
  {
    "name": "파도 가오리",
    "description": "얕은 산호 바다의 파도 가오리. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 3,
    "slot": 6,
    "tier": 3,
    "color": "#8ed8cd",
    "shape": "bird"
  },
  {
    "name": "분홍 산호거북",
    "description": "얕은 산호 바다의 분홍 산호거북. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 3,
    "slot": 7,
    "tier": 4,
    "color": "#8ed8cd",
    "shape": "shell"
  },
  {
    "name": "노을 돌고래",
    "description": "얕은 산호 바다의 노을 돌고래. 꼬리지느러미를 흔들며 공중을 헤엄칩니다.",
    "stageId": 3,
    "slot": 8,
    "tier": 5,
    "color": "#8ed8cd",
    "shape": "fish"
  },
  {
    "name": "산호궁 바다용",
    "description": "얕은 산호 바다의 산호궁 바다용. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 3,
    "slot": 9,
    "tier": 6,
    "color": "#8ed8cd",
    "shape": "dragon"
  },
  {
    "name": "숯덩이 두두",
    "description": "화산 입구의 숯덩이 두두. 발 없이 둥실 떠다니며 잠든 추억을 깨웁니다.",
    "stageId": 4,
    "slot": 0,
    "tier": 0,
    "color": "#625e63",
    "shape": "spirit"
  },
  {
    "name": "불씨 도마뱀",
    "description": "화산 입구의 불씨 도마뱀. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 4,
    "slot": 1,
    "tier": 0,
    "color": "#625e63",
    "shape": "quadruped"
  },
  {
    "name": "화로 꼬북",
    "description": "화산 입구의 화로 꼬북. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 4,
    "slot": 2,
    "tier": 1,
    "color": "#625e63",
    "shape": "shell"
  },
  {
    "name": "재구름 박쥐",
    "description": "화산 입구의 재구름 박쥐. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 4,
    "slot": 3,
    "tier": 1,
    "color": "#625e63",
    "shape": "bird"
  },
  {
    "name": "유황 뿔양",
    "description": "화산 입구의 유황 뿔양. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 4,
    "slot": 4,
    "tier": 2,
    "color": "#625e63",
    "shape": "quadruped"
  },
  {
    "name": "용암 달팽이",
    "description": "화산 입구의 용암 달팽이. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 4,
    "slot": 5,
    "tier": 2,
    "color": "#625e63",
    "shape": "shell"
  },
  {
    "name": "흑요석 전갈",
    "description": "화산 입구의 흑요석 전갈. 여러 갈래 팔로 호기심 가는 물건을 만져 봅니다.",
    "stageId": 4,
    "slot": 6,
    "tier": 3,
    "color": "#625e63",
    "shape": "tentacle"
  },
  {
    "name": "분화구 멧돼지",
    "description": "화산 입구의 분화구 멧돼지. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 4,
    "slot": 7,
    "tier": 4,
    "color": "#625e63",
    "shape": "quadruped"
  },
  {
    "name": "불꽃 불사조",
    "description": "화산 입구의 불꽃 불사조. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 4,
    "slot": 8,
    "tier": 5,
    "color": "#625e63",
    "shape": "bird"
  },
  {
    "name": "심장불 화산룡",
    "description": "화산 입구의 심장불 화산룡. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 4,
    "slot": 9,
    "tier": 6,
    "color": "#625e63",
    "shape": "dragon"
  },
  {
    "name": "등불 아귀",
    "description": "크라켄 심해의 등불 아귀. 꼬리지느러미를 흔들며 공중을 헤엄칩니다.",
    "stageId": 5,
    "slot": 0,
    "tier": 0,
    "color": "#355979",
    "shape": "fish"
  },
  {
    "name": "유리 해파리",
    "description": "크라켄 심해의 유리 해파리. 여러 갈래 팔로 호기심 가는 물건을 만져 봅니다.",
    "stageId": 5,
    "slot": 1,
    "tier": 0,
    "color": "#355979",
    "shape": "tentacle"
  },
  {
    "name": "먹물 꼬마문어",
    "description": "크라켄 심해의 먹물 꼬마문어. 여러 갈래 팔로 호기심 가는 물건을 만져 봅니다.",
    "stageId": 5,
    "slot": 2,
    "tier": 1,
    "color": "#355979",
    "shape": "tentacle"
  },
  {
    "name": "해저 소라게",
    "description": "크라켄 심해의 해저 소라게. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 5,
    "slot": 3,
    "tier": 1,
    "color": "#355979",
    "shape": "shell"
  },
  {
    "name": "잠수함 복어",
    "description": "크라켄 심해의 잠수함 복어. 꼬리지느러미를 흔들며 공중을 헤엄칩니다.",
    "stageId": 5,
    "slot": 4,
    "tier": 2,
    "color": "#355979",
    "shape": "fish"
  },
  {
    "name": "발광 오징어",
    "description": "크라켄 심해의 발광 오징어. 여러 갈래 팔로 호기심 가는 물건을 만져 봅니다.",
    "stageId": 5,
    "slot": 5,
    "tier": 2,
    "color": "#355979",
    "shape": "tentacle"
  },
  {
    "name": "해구 리본장어",
    "description": "크라켄 심해의 해구 리본장어. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 5,
    "slot": 6,
    "tier": 3,
    "color": "#355979",
    "shape": "dragon"
  },
  {
    "name": "유적 갑옷게",
    "description": "크라켄 심해의 유적 갑옷게. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 5,
    "slot": 7,
    "tier": 4,
    "color": "#355979",
    "shape": "shell"
  },
  {
    "name": "달빛 만타",
    "description": "크라켄 심해의 달빛 만타. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 5,
    "slot": 8,
    "tier": 5,
    "color": "#355979",
    "shape": "bird"
  },
  {
    "name": "심해별 고래",
    "description": "크라켄 심해의 심해별 고래. 꼬리지느러미를 흔들며 공중을 헤엄칩니다.",
    "stageId": 5,
    "slot": 9,
    "tier": 6,
    "color": "#355979",
    "shape": "fish"
  },
  {
    "name": "분필 꼬마령",
    "description": "유령 학교의 분필 꼬마령. 발 없이 둥실 떠다니며 잠든 추억을 깨웁니다.",
    "stageId": 6,
    "slot": 0,
    "tier": 0,
    "color": "#827786",
    "shape": "spirit"
  },
  {
    "name": "지우개 먼지",
    "description": "유령 학교의 지우개 먼지. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 6,
    "slot": 1,
    "tier": 0,
    "color": "#827786",
    "shape": "quadruped"
  },
  {
    "name": "책갈피 부엉",
    "description": "유령 학교의 책갈피 부엉. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 6,
    "slot": 2,
    "tier": 1,
    "color": "#827786",
    "shape": "bird"
  },
  {
    "name": "사물함 숨바꼭",
    "description": "유령 학교의 사물함 숨바꼭. 관절과 장치를 달그락거리며 부지런히 따라옵니다.",
    "stageId": 6,
    "slot": 3,
    "tier": 1,
    "color": "#827786",
    "shape": "machine"
  },
  {
    "name": "잉크병 유령",
    "description": "유령 학교의 잉크병 유령. 발 없이 둥실 떠다니며 잠든 추억을 깨웁니다.",
    "stageId": 6,
    "slot": 4,
    "tier": 2,
    "color": "#827786",
    "shape": "spirit"
  },
  {
    "name": "시험지 종이학",
    "description": "유령 학교의 시험지 종이학. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 6,
    "slot": 5,
    "tier": 2,
    "color": "#827786",
    "shape": "bird"
  },
  {
    "name": "종지기 박쥐",
    "description": "유령 학교의 종지기 박쥐. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 6,
    "slot": 6,
    "tier": 3,
    "color": "#827786",
    "shape": "bird"
  },
  {
    "name": "교복 마법토끼",
    "description": "유령 학교의 교복 마법토끼. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 6,
    "slot": 7,
    "tier": 4,
    "color": "#827786",
    "shape": "rabbit"
  },
  {
    "name": "칠판 낙서룡",
    "description": "유령 학교의 칠판 낙서룡. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 6,
    "slot": 8,
    "tier": 5,
    "color": "#827786",
    "shape": "dragon"
  },
  {
    "name": "자정 교장부엉",
    "description": "유령 학교의 자정 교장부엉. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 6,
    "slot": 9,
    "tier": 6,
    "color": "#827786",
    "shape": "bird"
  },
  {
    "name": "픽셀 삐약",
    "description": "네온 사이버시티의 픽셀 삐약. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 7,
    "slot": 0,
    "tier": 0,
    "color": "#354569",
    "shape": "bird"
  },
  {
    "name": "배터리 햄찌",
    "description": "네온 사이버시티의 배터리 햄찌. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 7,
    "slot": 1,
    "tier": 0,
    "color": "#354569",
    "shape": "quadruped"
  },
  {
    "name": "와이파이 토끼",
    "description": "네온 사이버시티의 와이파이 토끼. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 7,
    "slot": 2,
    "tier": 1,
    "color": "#354569",
    "shape": "rabbit"
  },
  {
    "name": "네온 신호등",
    "description": "네온 사이버시티의 네온 신호등. 관절과 장치를 달그락거리며 부지런히 따라옵니다.",
    "stageId": 7,
    "slot": 3,
    "tier": 1,
    "color": "#354569",
    "shape": "machine"
  },
  {
    "name": "홀로그램 고양",
    "description": "네온 사이버시티의 홀로그램 고양. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 7,
    "slot": 4,
    "tier": 2,
    "color": "#354569",
    "shape": "quadruped"
  },
  {
    "name": "회로 등딱지",
    "description": "네온 사이버시티의 회로 등딱지. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 7,
    "slot": 5,
    "tier": 2,
    "color": "#354569",
    "shape": "shell"
  },
  {
    "name": "스피커 해파리",
    "description": "네온 사이버시티의 스피커 해파리. 여러 갈래 팔로 호기심 가는 물건을 만져 봅니다.",
    "stageId": 7,
    "slot": 6,
    "tier": 3,
    "color": "#354569",
    "shape": "tentacle"
  },
  {
    "name": "호버보드 여우",
    "description": "네온 사이버시티의 호버보드 여우. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 7,
    "slot": 7,
    "tier": 4,
    "color": "#354569",
    "shape": "quadruped"
  },
  {
    "name": "레이저 날개룡",
    "description": "네온 사이버시티의 레이저 날개룡. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 7,
    "slot": 8,
    "tier": 5,
    "color": "#354569",
    "shape": "dragon"
  },
  {
    "name": "도시 코어기린",
    "description": "네온 사이버시티의 도시 코어기린. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 7,
    "slot": 9,
    "tier": 6,
    "color": "#354569",
    "shape": "quadruped"
  },
  {
    "name": "모래 귀쫑",
    "description": "황금 사막왕국의 모래 귀쫑. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 8,
    "slot": 0,
    "tier": 0,
    "color": "#d9b16d",
    "shape": "rabbit"
  },
  {
    "name": "오아시스 새싹",
    "description": "황금 사막왕국의 오아시스 새싹. 머리 위 싹을 돌보며 작은 빛을 나눠 줍니다.",
    "stageId": 8,
    "slot": 1,
    "tier": 0,
    "color": "#d9b16d",
    "shape": "plant"
  },
  {
    "name": "항아리 소라",
    "description": "황금 사막왕국의 항아리 소라. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 8,
    "slot": 2,
    "tier": 1,
    "color": "#d9b16d",
    "shape": "shell"
  },
  {
    "name": "황동 풍뎅이",
    "description": "황금 사막왕국의 황동 풍뎅이. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 8,
    "slot": 3,
    "tier": 1,
    "color": "#d9b16d",
    "shape": "shell"
  },
  {
    "name": "대추 낙타",
    "description": "황금 사막왕국의 대추 낙타. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 8,
    "slot": 4,
    "tier": 2,
    "color": "#d9b16d",
    "shape": "quadruped"
  },
  {
    "name": "비단 코브라",
    "description": "황금 사막왕국의 비단 코브라. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 8,
    "slot": 5,
    "tier": 2,
    "color": "#d9b16d",
    "shape": "dragon"
  },
  {
    "name": "모래시계 여우",
    "description": "황금 사막왕국의 모래시계 여우. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 8,
    "slot": 6,
    "tier": 3,
    "color": "#d9b16d",
    "shape": "quadruped"
  },
  {
    "name": "태양 매",
    "description": "황금 사막왕국의 태양 매. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 8,
    "slot": 7,
    "tier": 4,
    "color": "#d9b16d",
    "shape": "bird"
  },
  {
    "name": "피라미드 스핑크스",
    "description": "황금 사막왕국의 피라미드 스핑크스. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 8,
    "slot": 8,
    "tier": 5,
    "color": "#d9b16d",
    "shape": "quadruped"
  },
  {
    "name": "황금 원반불사조",
    "description": "황금 사막왕국의 황금 원반불사조. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 8,
    "slot": 9,
    "tier": 6,
    "color": "#d9b16d",
    "shape": "bird"
  },
  {
    "name": "양치 새순",
    "description": "태초의 공룡섬의 양치 새순. 머리 위 싹을 돌보며 작은 빛을 나눠 줍니다.",
    "stageId": 9,
    "slot": 0,
    "tier": 0,
    "color": "#759379",
    "shape": "plant"
  },
  {
    "name": "호박 송충",
    "description": "태초의 공룡섬의 호박 송충. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 9,
    "slot": 1,
    "tier": 0,
    "color": "#759379",
    "shape": "quadruped"
  },
  {
    "name": "화석 암모",
    "description": "태초의 공룡섬의 화석 암모. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 9,
    "slot": 2,
    "tier": 1,
    "color": "#759379",
    "shape": "shell"
  },
  {
    "name": "깃털 랩터",
    "description": "태초의 공룡섬의 깃털 랩터. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 9,
    "slot": 3,
    "tier": 1,
    "color": "#759379",
    "shape": "bird"
  },
  {
    "name": "꼬마 트리케라",
    "description": "태초의 공룡섬의 꼬마 트리케라. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 9,
    "slot": 4,
    "tier": 2,
    "color": "#759379",
    "shape": "quadruped"
  },
  {
    "name": "바위 안킬로",
    "description": "태초의 공룡섬의 바위 안킬로. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 9,
    "slot": 5,
    "tier": 2,
    "color": "#759379",
    "shape": "shell"
  },
  {
    "name": "돛등 스피노",
    "description": "태초의 공룡섬의 돛등 스피노. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 9,
    "slot": 6,
    "tier": 3,
    "color": "#759379",
    "shape": "dragon"
  },
  {
    "name": "긴목 브라키오",
    "description": "태초의 공룡섬의 긴목 브라키오. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 9,
    "slot": 7,
    "tier": 4,
    "color": "#759379",
    "shape": "dragon"
  },
  {
    "name": "하늘 익룡",
    "description": "태초의 공룡섬의 하늘 익룡. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 9,
    "slot": 8,
    "tier": 5,
    "color": "#759379",
    "shape": "bird"
  },
  {
    "name": "태초의 세계수룡",
    "description": "태초의 공룡섬의 태초의 세계수룡. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 9,
    "slot": 9,
    "tier": 6,
    "color": "#759379",
    "shape": "dragon"
  },
  {
    "name": "호롱 불씨",
    "description": "도깨비 달마을의 호롱 불씨. 발 없이 둥실 떠다니며 잠든 추억을 깨웁니다.",
    "stageId": 10,
    "slot": 0,
    "tier": 0,
    "color": "#574765",
    "shape": "spirit"
  },
  {
    "name": "기와 고양",
    "description": "도깨비 달마을의 기와 고양. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 10,
    "slot": 1,
    "tier": 0,
    "color": "#574765",
    "shape": "quadruped"
  },
  {
    "name": "방망이 콩깨비",
    "description": "도깨비 달마을의 방망이 콩깨비. 관절과 장치를 달그락거리며 부지런히 따라옵니다.",
    "stageId": 10,
    "slot": 2,
    "tier": 1,
    "color": "#574765",
    "shape": "machine"
  },
  {
    "name": "달떡 토끼",
    "description": "도깨비 달마을의 달떡 토끼. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 10,
    "slot": 3,
    "tier": 1,
    "color": "#574765",
    "shape": "rabbit"
  },
  {
    "name": "장독 숨숨",
    "description": "도깨비 달마을의 장독 숨숨. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 10,
    "slot": 4,
    "tier": 2,
    "color": "#574765",
    "shape": "shell"
  },
  {
    "name": "부채 까치",
    "description": "도깨비 달마을의 부채 까치. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 10,
    "slot": 5,
    "tier": 2,
    "color": "#574765",
    "shape": "bird"
  },
  {
    "name": "구미호 홍련",
    "description": "도깨비 달마을의 구미호 홍련. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 10,
    "slot": 6,
    "tier": 3,
    "color": "#574765",
    "shape": "quadruped"
  },
  {
    "name": "도깨비 북지기",
    "description": "도깨비 달마을의 도깨비 북지기. 관절과 장치를 달그락거리며 부지런히 따라옵니다.",
    "stageId": 10,
    "slot": 7,
    "tier": 4,
    "color": "#574765",
    "shape": "machine"
  },
  {
    "name": "붉은달 해태",
    "description": "도깨비 달마을의 붉은달 해태. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 10,
    "slot": 8,
    "tier": 5,
    "color": "#574765",
    "shape": "quadruped"
  },
  {
    "name": "소원불 기린",
    "description": "도깨비 달마을의 소원불 기린. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 10,
    "slot": 9,
    "tier": 6,
    "color": "#574765",
    "shape": "dragon"
  },
  {
    "name": "구름 솜양",
    "description": "올림포스 신전의 구름 솜양. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 11,
    "slot": 0,
    "tier": 0,
    "color": "#d9ddec",
    "shape": "quadruped"
  },
  {
    "name": "월계 새싹",
    "description": "올림포스 신전의 월계 새싹. 머리 위 싹을 돌보며 작은 빛을 나눠 줍니다.",
    "stageId": 11,
    "slot": 1,
    "tier": 0,
    "color": "#d9ddec",
    "shape": "plant"
  },
  {
    "name": "대리석 꼬북",
    "description": "올림포스 신전의 대리석 꼬북. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 11,
    "slot": 2,
    "tier": 1,
    "color": "#d9ddec",
    "shape": "shell"
  },
  {
    "name": "리라 종달",
    "description": "올림포스 신전의 리라 종달. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 11,
    "slot": 3,
    "tier": 1,
    "color": "#d9ddec",
    "shape": "bird"
  },
  {
    "name": "번개 다람",
    "description": "올림포스 신전의 번개 다람. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 11,
    "slot": 4,
    "tier": 2,
    "color": "#d9ddec",
    "shape": "quadruped"
  },
  {
    "name": "날개 샌들토끼",
    "description": "올림포스 신전의 날개 샌들토끼. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 11,
    "slot": 5,
    "tier": 2,
    "color": "#d9ddec",
    "shape": "rabbit"
  },
  {
    "name": "황금 독수리",
    "description": "올림포스 신전의 황금 독수리. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 11,
    "slot": 6,
    "tier": 3,
    "color": "#d9ddec",
    "shape": "bird"
  },
  {
    "name": "샘물 페가수스",
    "description": "올림포스 신전의 샘물 페가수스. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 11,
    "slot": 7,
    "tier": 4,
    "color": "#d9ddec",
    "shape": "quadruped"
  },
  {
    "name": "별갑옷 그리핀",
    "description": "올림포스 신전의 별갑옷 그리핀. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 11,
    "slot": 8,
    "tier": 5,
    "color": "#d9ddec",
    "shape": "dragon"
  },
  {
    "name": "천둥 왕관사자",
    "description": "올림포스 신전의 천둥 왕관사자. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 11,
    "slot": 9,
    "tier": 6,
    "color": "#d9ddec",
    "shape": "quadruped"
  },
  {
    "name": "촉수 콩별",
    "description": "외계인 51구역의 촉수 콩별. 여러 갈래 팔로 호기심 가는 물건을 만져 봅니다.",
    "stageId": 12,
    "slot": 0,
    "tier": 0,
    "color": "#5f6589",
    "shape": "tentacle"
  },
  {
    "name": "외눈 젤리",
    "description": "외계인 51구역의 외눈 젤리. 발 없이 둥실 떠다니며 잠든 추억을 깨웁니다.",
    "stageId": 12,
    "slot": 1,
    "tier": 0,
    "color": "#5f6589",
    "shape": "spirit"
  },
  {
    "name": "탐사 로버",
    "description": "외계인 51구역의 탐사 로버. 관절과 장치를 달그락거리며 부지런히 따라옵니다.",
    "stageId": 12,
    "slot": 2,
    "tier": 1,
    "color": "#5f6589",
    "shape": "machine"
  },
  {
    "name": "접시 달팽이",
    "description": "외계인 51구역의 접시 달팽이. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 12,
    "slot": 3,
    "tier": 1,
    "color": "#5f6589",
    "shape": "shell"
  },
  {
    "name": "안테나 토끼",
    "description": "외계인 51구역의 안테나 토끼. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 12,
    "slot": 4,
    "tier": 2,
    "color": "#5f6589",
    "shape": "rabbit"
  },
  {
    "name": "형광 우파루파",
    "description": "외계인 51구역의 형광 우파루파. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 12,
    "slot": 5,
    "tier": 2,
    "color": "#5f6589",
    "shape": "quadruped"
  },
  {
    "name": "무중력 오징어",
    "description": "외계인 51구역의 무중력 오징어. 여러 갈래 팔로 호기심 가는 물건을 만져 봅니다.",
    "stageId": 12,
    "slot": 6,
    "tier": 3,
    "color": "#5f6589",
    "shape": "tentacle"
  },
  {
    "name": "수정 원자로봇",
    "description": "외계인 51구역의 수정 원자로봇. 관절과 장치를 달그락거리며 부지런히 따라옵니다.",
    "stageId": 12,
    "slot": 7,
    "tier": 4,
    "color": "#5f6589",
    "shape": "machine"
  },
  {
    "name": "성운 비행가오리",
    "description": "외계인 51구역의 성운 비행가오리. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 12,
    "slot": 8,
    "tier": 5,
    "color": "#5f6589",
    "shape": "bird"
  },
  {
    "name": "모선 품은 고래",
    "description": "외계인 51구역의 모선 품은 고래. 꼬리지느러미를 흔들며 공중을 헤엄칩니다.",
    "stageId": 12,
    "slot": 9,
    "tier": 6,
    "color": "#5f6589",
    "shape": "fish"
  },
  {
    "name": "리벳 참새",
    "description": "스팀펑크 공중도시의 리벳 참새. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 13,
    "slot": 0,
    "tier": 0,
    "color": "#b28d69",
    "shape": "bird"
  },
  {
    "name": "증기 주전자",
    "description": "스팀펑크 공중도시의 증기 주전자. 관절과 장치를 달그락거리며 부지런히 따라옵니다.",
    "stageId": 13,
    "slot": 1,
    "tier": 0,
    "color": "#b28d69",
    "shape": "machine"
  },
  {
    "name": "톱니 햄스터",
    "description": "스팀펑크 공중도시의 톱니 햄스터. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 13,
    "slot": 2,
    "tier": 1,
    "color": "#b28d69",
    "shape": "quadruped"
  },
  {
    "name": "나침반 거북",
    "description": "스팀펑크 공중도시의 나침반 거북. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 13,
    "slot": 3,
    "tier": 1,
    "color": "#b28d69",
    "shape": "shell"
  },
  {
    "name": "고글 비행토끼",
    "description": "스팀펑크 공중도시의 고글 비행토끼. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 13,
    "slot": 4,
    "tier": 2,
    "color": "#b28d69",
    "shape": "rabbit"
  },
  {
    "name": "굴뚝 펭귄",
    "description": "스팀펑크 공중도시의 굴뚝 펭귄. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 13,
    "slot": 5,
    "tier": 2,
    "color": "#b28d69",
    "shape": "bird"
  },
  {
    "name": "프로펠러 여우",
    "description": "스팀펑크 공중도시의 프로펠러 여우. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 13,
    "slot": 6,
    "tier": 3,
    "color": "#b28d69",
    "shape": "quadruped"
  },
  {
    "name": "비행선 고래",
    "description": "스팀펑크 공중도시의 비행선 고래. 꼬리지느러미를 흔들며 공중을 헤엄칩니다.",
    "stageId": 13,
    "slot": 7,
    "tier": 4,
    "color": "#b28d69",
    "shape": "fish"
  },
  {
    "name": "시계탑 올빼미",
    "description": "스팀펑크 공중도시의 시계탑 올빼미. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 13,
    "slot": 8,
    "tier": 5,
    "color": "#b28d69",
    "shape": "bird"
  },
  {
    "name": "황동 심장용",
    "description": "스팀펑크 공중도시의 황동 심장용. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 13,
    "slot": 9,
    "tier": 6,
    "color": "#b28d69",
    "shape": "dragon"
  },
  {
    "name": "눈송이 포포",
    "description": "영원의 빙하의 눈송이 포포. 발 없이 둥실 떠다니며 잠든 추억을 깨웁니다.",
    "stageId": 14,
    "slot": 0,
    "tier": 0,
    "color": "#b1dbe8",
    "shape": "spirit"
  },
  {
    "name": "목도리 펭귄",
    "description": "영원의 빙하의 목도리 펭귄. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 14,
    "slot": 1,
    "tier": 0,
    "color": "#b1dbe8",
    "shape": "bird"
  },
  {
    "name": "서리 토끼",
    "description": "영원의 빙하의 서리 토끼. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 14,
    "slot": 2,
    "tier": 1,
    "color": "#b1dbe8",
    "shape": "rabbit"
  },
  {
    "name": "빙판 물범",
    "description": "영원의 빙하의 빙판 물범. 꼬리지느러미를 흔들며 공중을 헤엄칩니다.",
    "stageId": 14,
    "slot": 3,
    "tier": 1,
    "color": "#b1dbe8",
    "shape": "fish"
  },
  {
    "name": "고드름 고슴",
    "description": "영원의 빙하의 고드름 고슴. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 14,
    "slot": 4,
    "tier": 2,
    "color": "#b1dbe8",
    "shape": "quadruped"
  },
  {
    "name": "수정 소라",
    "description": "영원의 빙하의 수정 소라. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 14,
    "slot": 5,
    "tier": 2,
    "color": "#b1dbe8",
    "shape": "shell"
  },
  {
    "name": "오로라 여우",
    "description": "영원의 빙하의 오로라 여우. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 14,
    "slot": 6,
    "tier": 3,
    "color": "#b1dbe8",
    "shape": "quadruped"
  },
  {
    "name": "얼음뿔 순록",
    "description": "영원의 빙하의 얼음뿔 순록. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 14,
    "slot": 7,
    "tier": 4,
    "color": "#b1dbe8",
    "shape": "quadruped"
  },
  {
    "name": "극광 날개새",
    "description": "영원의 빙하의 극광 날개새. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 14,
    "slot": 8,
    "tier": 5,
    "color": "#b1dbe8",
    "shape": "bird"
  },
  {
    "name": "영원빙하 백룡",
    "description": "영원의 빙하의 영원빙하 백룡. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 14,
    "slot": 9,
    "tier": 6,
    "color": "#b1dbe8",
    "shape": "dragon"
  },
  {
    "name": "베개 꾸벅",
    "description": "뒤죽박죽 꿈나라의 베개 꾸벅. 발 없이 둥실 떠다니며 잠든 추억을 깨웁니다.",
    "stageId": 15,
    "slot": 0,
    "tier": 0,
    "color": "#d4bbdc",
    "shape": "spirit"
  },
  {
    "name": "별사탕 쥐",
    "description": "뒤죽박죽 꿈나라의 별사탕 쥐. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 15,
    "slot": 1,
    "tier": 0,
    "color": "#d4bbdc",
    "shape": "quadruped"
  },
  {
    "name": "잠옷 토끼",
    "description": "뒤죽박죽 꿈나라의 잠옷 토끼. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 15,
    "slot": 2,
    "tier": 1,
    "color": "#d4bbdc",
    "shape": "rabbit"
  },
  {
    "name": "찻잔 달팽이",
    "description": "뒤죽박죽 꿈나라의 찻잔 달팽이. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 15,
    "slot": 3,
    "tier": 1,
    "color": "#d4bbdc",
    "shape": "shell"
  },
  {
    "name": "거꾸로 시계새",
    "description": "뒤죽박죽 꿈나라의 거꾸로 시계새. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 15,
    "slot": 4,
    "tier": 2,
    "color": "#d4bbdc",
    "shape": "bird"
  },
  {
    "name": "풍선 코끼리",
    "description": "뒤죽박죽 꿈나라의 풍선 코끼리. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 15,
    "slot": 5,
    "tier": 2,
    "color": "#d4bbdc",
    "shape": "quadruped"
  },
  {
    "name": "꿈실 해파리",
    "description": "뒤죽박죽 꿈나라의 꿈실 해파리. 여러 갈래 팔로 호기심 가는 물건을 만져 봅니다.",
    "stageId": 15,
    "slot": 6,
    "tier": 3,
    "color": "#d4bbdc",
    "shape": "tentacle"
  },
  {
    "name": "달그네 고양",
    "description": "뒤죽박죽 꿈나라의 달그네 고양. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 15,
    "slot": 7,
    "tier": 4,
    "color": "#d4bbdc",
    "shape": "quadruped"
  },
  {
    "name": "무지개 이불고래",
    "description": "뒤죽박죽 꿈나라의 무지개 이불고래. 꼬리지느러미를 흔들며 공중을 헤엄칩니다.",
    "stageId": 15,
    "slot": 8,
    "tier": 5,
    "color": "#d4bbdc",
    "shape": "fish"
  },
  {
    "name": "꿈을 짓는 나비룡",
    "description": "뒤죽박죽 꿈나라의 꿈을 짓는 나비룡. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 15,
    "slot": 9,
    "tier": 6,
    "color": "#d4bbdc",
    "shape": "dragon"
  },
  {
    "name": "녹슨 통통",
    "description": "방사능 폐허의 녹슨 통통. 관절과 장치를 달그락거리며 부지런히 따라옵니다.",
    "stageId": 16,
    "slot": 0,
    "tier": 0,
    "color": "#6d8058",
    "shape": "machine"
  },
  {
    "name": "형광 이끼",
    "description": "방사능 폐허의 형광 이끼. 머리 위 싹을 돌보며 작은 빛을 나눠 줍니다.",
    "stageId": 16,
    "slot": 1,
    "tier": 0,
    "color": "#6d8058",
    "shape": "plant"
  },
  {
    "name": "방독면 쥐",
    "description": "방사능 폐허의 방독면 쥐. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 16,
    "slot": 2,
    "tier": 1,
    "color": "#6d8058",
    "shape": "quadruped"
  },
  {
    "name": "유리 버섯",
    "description": "방사능 폐허의 유리 버섯. 머리 위 싹을 돌보며 작은 빛을 나눠 줍니다.",
    "stageId": 16,
    "slot": 3,
    "tier": 1,
    "color": "#6d8058",
    "shape": "plant"
  },
  {
    "name": "세눈 두꺼비",
    "description": "방사능 폐허의 세눈 두꺼비. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 16,
    "slot": 4,
    "tier": 2,
    "color": "#6d8058",
    "shape": "quadruped"
  },
  {
    "name": "폐전지 거북",
    "description": "방사능 폐허의 폐전지 거북. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 16,
    "slot": 5,
    "tier": 2,
    "color": "#6d8058",
    "shape": "shell"
  },
  {
    "name": "변이 덩굴문어",
    "description": "방사능 폐허의 변이 덩굴문어. 여러 갈래 팔로 호기심 가는 물건을 만져 봅니다.",
    "stageId": 16,
    "slot": 6,
    "tier": 3,
    "color": "#6d8058",
    "shape": "tentacle"
  },
  {
    "name": "독안개 까마귀",
    "description": "방사능 폐허의 독안개 까마귀. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 16,
    "slot": 7,
    "tier": 4,
    "color": "#6d8058",
    "shape": "bird"
  },
  {
    "name": "정화수 사슴",
    "description": "방사능 폐허의 정화수 사슴. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 16,
    "slot": 8,
    "tier": 5,
    "color": "#6d8058",
    "shape": "quadruped"
  },
  {
    "name": "재생의 꽃드래곤",
    "description": "방사능 폐허의 재생의 꽃드래곤. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 16,
    "slot": 9,
    "tier": 6,
    "color": "#6d8058",
    "shape": "dragon"
  },
  {
    "name": "이슬 진딧",
    "description": "곤충 소인국의 이슬 진딧. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 17,
    "slot": 0,
    "tier": 0,
    "color": "#91ad63",
    "shape": "quadruped"
  },
  {
    "name": "잎말이 꼬물",
    "description": "곤충 소인국의 잎말이 꼬물. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 17,
    "slot": 1,
    "tier": 0,
    "color": "#91ad63",
    "shape": "shell"
  },
  {
    "name": "점박 무당",
    "description": "곤충 소인국의 점박 무당. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 17,
    "slot": 2,
    "tier": 1,
    "color": "#91ad63",
    "shape": "shell"
  },
  {
    "name": "꿀벌 붕붕",
    "description": "곤충 소인국의 꿀벌 붕붕. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 17,
    "slot": 3,
    "tier": 1,
    "color": "#91ad63",
    "shape": "bird"
  },
  {
    "name": "풀잎 메뚜기",
    "description": "곤충 소인국의 풀잎 메뚜기. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 17,
    "slot": 4,
    "tier": 2,
    "color": "#91ad63",
    "shape": "rabbit"
  },
  {
    "name": "실뽑는 거미",
    "description": "곤충 소인국의 실뽑는 거미. 여러 갈래 팔로 호기심 가는 물건을 만져 봅니다.",
    "stageId": 17,
    "slot": 5,
    "tier": 2,
    "color": "#91ad63",
    "shape": "tentacle"
  },
  {
    "name": "꽃잎 사마귀",
    "description": "곤충 소인국의 꽃잎 사마귀. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 17,
    "slot": 6,
    "tier": 3,
    "color": "#91ad63",
    "shape": "quadruped"
  },
  {
    "name": "장수 투구벌레",
    "description": "곤충 소인국의 장수 투구벌레. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 17,
    "slot": 7,
    "tier": 4,
    "color": "#91ad63",
    "shape": "shell"
  },
  {
    "name": "달빛 나방",
    "description": "곤충 소인국의 달빛 나방. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 17,
    "slot": 8,
    "tier": 5,
    "color": "#91ad63",
    "shape": "bird"
  },
  {
    "name": "숲왕 유리나비",
    "description": "곤충 소인국의 숲왕 유리나비. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 17,
    "slot": 9,
    "tier": 6,
    "color": "#91ad63",
    "shape": "dragon"
  },
  {
    "name": "볼트 또각",
    "description": "고철 로봇행성의 볼트 또각. 관절과 장치를 달그락거리며 부지런히 따라옵니다.",
    "stageId": 18,
    "slot": 0,
    "tier": 0,
    "color": "#7c8088",
    "shape": "machine"
  },
  {
    "name": "너트 굴렁",
    "description": "고철 로봇행성의 너트 굴렁. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 18,
    "slot": 1,
    "tier": 0,
    "color": "#7c8088",
    "shape": "shell"
  },
  {
    "name": "고철 강아지",
    "description": "고철 로봇행성의 고철 강아지. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 18,
    "slot": 2,
    "tier": 1,
    "color": "#7c8088",
    "shape": "quadruped"
  },
  {
    "name": "스프링 토끼",
    "description": "고철 로봇행성의 스프링 토끼. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 18,
    "slot": 3,
    "tier": 1,
    "color": "#7c8088",
    "shape": "rabbit"
  },
  {
    "name": "집게 청소봇",
    "description": "고철 로봇행성의 집게 청소봇. 여러 갈래 팔로 호기심 가는 물건을 만져 봅니다.",
    "stageId": 18,
    "slot": 4,
    "tier": 2,
    "color": "#7c8088",
    "shape": "tentacle"
  },
  {
    "name": "무한궤도 꼬북",
    "description": "고철 로봇행성의 무한궤도 꼬북. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 18,
    "slot": 5,
    "tier": 2,
    "color": "#7c8088",
    "shape": "shell"
  },
  {
    "name": "자석 날개새",
    "description": "고철 로봇행성의 자석 날개새. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 18,
    "slot": 6,
    "tier": 3,
    "color": "#7c8088",
    "shape": "bird"
  },
  {
    "name": "용접 불꽃사자",
    "description": "고철 로봇행성의 용접 불꽃사자. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 18,
    "slot": 7,
    "tier": 4,
    "color": "#7c8088",
    "shape": "quadruped"
  },
  {
    "name": "폐선 우주고래",
    "description": "고철 로봇행성의 폐선 우주고래. 꼬리지느러미를 흔들며 공중을 헤엄칩니다.",
    "stageId": 18,
    "slot": 8,
    "tier": 5,
    "color": "#7c8088",
    "shape": "fish"
  },
  {
    "name": "행성 재조립룡",
    "description": "고철 로봇행성의 행성 재조립룡. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 18,
    "slot": 9,
    "tier": 6,
    "color": "#7c8088",
    "shape": "dragon"
  },
  {
    "name": "별가루 병아리",
    "description": "은하수 천문대의 별가루 병아리. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 19,
    "slot": 0,
    "tier": 0,
    "color": "#565380",
    "shape": "bird"
  },
  {
    "name": "달조각 토끼",
    "description": "은하수 천문대의 달조각 토끼. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 19,
    "slot": 1,
    "tier": 0,
    "color": "#565380",
    "shape": "rabbit"
  },
  {
    "name": "혜성 꼬리쥐",
    "description": "은하수 천문대의 혜성 꼬리쥐. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 19,
    "slot": 2,
    "tier": 1,
    "color": "#565380",
    "shape": "quadruped"
  },
  {
    "name": "고리행성 거북",
    "description": "은하수 천문대의 고리행성 거북. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 19,
    "slot": 3,
    "tier": 1,
    "color": "#565380",
    "shape": "shell"
  },
  {
    "name": "망원경 부엉",
    "description": "은하수 천문대의 망원경 부엉. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 19,
    "slot": 4,
    "tier": 2,
    "color": "#565380",
    "shape": "bird"
  },
  {
    "name": "운석 소라게",
    "description": "은하수 천문대의 운석 소라게. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 19,
    "slot": 5,
    "tier": 2,
    "color": "#565380",
    "shape": "shell"
  },
  {
    "name": "별자리 사슴",
    "description": "은하수 천문대의 별자리 사슴. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 19,
    "slot": 6,
    "tier": 3,
    "color": "#565380",
    "shape": "quadruped"
  },
  {
    "name": "은하 리본용",
    "description": "은하수 천문대의 은하 리본용. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 19,
    "slot": 7,
    "tier": 4,
    "color": "#565380",
    "shape": "dragon"
  },
  {
    "name": "초신성 봉황",
    "description": "은하수 천문대의 초신성 봉황. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 19,
    "slot": 8,
    "tier": 5,
    "color": "#565380",
    "shape": "bird"
  },
  {
    "name": "밤하늘 유영고래",
    "description": "은하수 천문대의 밤하늘 유영고래. 꼬리지느러미를 흔들며 공중을 헤엄칩니다.",
    "stageId": 19,
    "slot": 9,
    "tier": 6,
    "color": "#565380",
    "shape": "fish"
  },
  {
    "name": "공허 점방울",
    "description": "공허와 창조주의 정원의 공허 점방울. 발 없이 둥실 떠다니며 잠든 추억을 깨웁니다.",
    "stageId": 20,
    "slot": 0,
    "tier": 0,
    "color": "#393145",
    "shape": "spirit"
  },
  {
    "name": "기억의 새싹",
    "description": "공허와 창조주의 정원의 기억의 새싹. 머리 위 싹을 돌보며 작은 빛을 나눠 줍니다.",
    "stageId": 20,
    "slot": 1,
    "tier": 0,
    "color": "#393145",
    "shape": "plant"
  },
  {
    "name": "차원문 꼬북",
    "description": "공허와 창조주의 정원의 차원문 꼬북. 단단한 등껍질에 소중한 보물을 숨겨 둡니다.",
    "stageId": 20,
    "slot": 2,
    "tier": 1,
    "color": "#393145",
    "shape": "shell"
  },
  {
    "name": "시간 모래토끼",
    "description": "공허와 창조주의 정원의 시간 모래토끼. 긴 귀로 먼 소리를 듣고 두 발로 통통 뛰어옵니다.",
    "stageId": 20,
    "slot": 3,
    "tier": 1,
    "color": "#393145",
    "shape": "rabbit"
  },
  {
    "name": "잊힌 이름새",
    "description": "공허와 창조주의 정원의 잊힌 이름새. 넓은 날개와 작은 부리로 길 위의 소식을 전합니다.",
    "stageId": 20,
    "slot": 4,
    "tier": 2,
    "color": "#393145",
    "shape": "bird"
  },
  {
    "name": "별씨 정원사",
    "description": "공허와 창조주의 정원의 별씨 정원사. 머리 위 싹을 돌보며 작은 빛을 나눠 줍니다.",
    "stageId": 20,
    "slot": 5,
    "tier": 2,
    "color": "#393145",
    "shape": "plant"
  },
  {
    "name": "기억실 해파리",
    "description": "공허와 창조주의 정원의 기억실 해파리. 여러 갈래 팔로 호기심 가는 물건을 만져 봅니다.",
    "stageId": 20,
    "slot": 6,
    "tier": 3,
    "color": "#393145",
    "shape": "tentacle"
  },
  {
    "name": "황금문 수호사슴",
    "description": "공허와 창조주의 정원의 황금문 수호사슴. 네 발로 종종거리며 꼬리로 기분을 표현합니다.",
    "stageId": 20,
    "slot": 7,
    "tier": 4,
    "color": "#393145",
    "shape": "quadruped"
  },
  {
    "name": "창조의 여섯날개",
    "description": "공허와 창조주의 정원의 창조의 여섯날개. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 20,
    "slot": 8,
    "tier": 5,
    "color": "#393145",
    "shape": "dragon"
  },
  {
    "name": "첫빛 세계수룡",
    "description": "공허와 창조주의 정원의 첫빛 세계수룡. 긴 꼬리와 뿔을 세우고 친구의 앞길을 지킵니다.",
    "stageId": 20,
    "slot": 9,
    "tier": 6,
    "color": "#393145",
    "shape": "dragon"
  }
];
